
from django.db import models

class Artisan(models.Model):
    start = models.DateTimeField(null=True,blank=True) # verbose_name='start'
    end = models.DateTimeField(null=True,blank=True) # verbose_name='end'
    col_0_1_NOM_DE_L_ENTREPRISE = models.CharField(max_length=255) # verbose_name='0.1. NOM DE L'ENTREPRISE:'
    col_0_2_NOM_DE_DU_TUTEUR = models.CharField(max_length=255) # verbose_name='0.2. NOM DE DU TUTEUR:'
    col_0_3_NOM_ET_PRENOMS_DE_L_ENQUETEUR = models.CharField(max_length=255) # verbose_name='0.3. NOM ET PRENOMS DE L'ENQUETEUR:'
    O_4_VILLE_DE_L_ENQUETE = models.CharField(max_length=255) # verbose_name='O.4. VILLE DE L’ENQUETE '
    Précisez_la_ville = models.CharField(max_length=255) # verbose_name='Précisez la ville'
    O_5_COMMUNE_VILLAGE_DE_L_ENQUETE = models.CharField(max_length=255) # verbose_name='O.5. COMMUNE / VILLAGE DE L’ENQUETE '
    Précisez_la_commune = models.CharField(max_length=255) # verbose_name='Précisez la commune'
    O_6_DATE_DE_L_ENQUETE = models.DateTimeField(null=True,blank=True) # verbose_name='O.6. DATE DE L’ENQUETE  '
    O_7_DEBUT_DE_L_ENQUETE = models.CharField(max_length=255) # verbose_name='O.7. DEBUT DE L’ENQUETE '
    col_1_1_Sexe_du_répondant = models.CharField(max_length=255) # verbose_name='1.1. Sexe du répondant'
    col_1_2_Statut_du_répondant = models.CharField(max_length=255) # verbose_name='1.2 Statut du répondant'
    Précisez_le_statut_du_répondant = models.CharField(max_length=255) # verbose_name='Précisez le statut du répondant'
    col_1_3_Quel_est_le_type_d_activité_exercé = models.CharField(max_length=255) # verbose_name='1.3 Quel est le type d'activité exercé ?'
    Précisez_l_activité = models.CharField(max_length=255) # verbose_name='Précisez l'activité'
    col_1_4_Quelle_est_votre_tranche_d_âge = models.CharField(max_length=255) # verbose_name='1.4. Quelle est votre tranche d'âge ?'
    col_1_5_Savez_vous_lire_ou_écrire = models.CharField(max_length=255) # verbose_name='1.5 Savez-vous lire ou écrire ?'
    col_1_6_Quel_est_votre_niveau_d_instruction = models.CharField(max_length=255) # verbose_name='1.6. Quel est votre niveau d’instruction ?'
    col_1_7_Avez_vous_eu_une_formation_ou_une_certification_relativ = models.CharField(max_length=255) # verbose_name='1.7. Avez-vous eu une formation ou une certification relative au métier que vous exercez ?'
    col_1_8_Quel_est_votre_situation_matrimoniale = models.CharField(max_length=255) # verbose_name='1.8. Quel est votre situation matrimoniale ?'
    col_1_9_De_quel_pays_êtes_vous_originaire = models.CharField(max_length=255) # verbose_name='1.9. De quel pays êtes-vous originaire ?'
    Précisez_le_pays = models.CharField(max_length=255) # verbose_name='Précisez le pays'
    col_1_10_Quel_est_la_date_de_création_de_votre_activité = models.CharField(max_length=255) # verbose_name='1.10. Quel est la date de création de votre activité ?'
    col_1_11_Nom_et_prénoms_du_répondant = models.CharField(max_length=255) # verbose_name='1.11. Nom et prénoms du répondant'
    col_1_12_Avez_vous_un_contact_téléphonique = models.CharField(max_length=255) # verbose_name='1.12. Avez-vous un contact téléphonique ?'
    col_1_13_Si_Oui_quel_est_votre_numéro_de_téléphone_principal = models.FloatField(null=True,blank=True) # verbose_name='1.13. Si Oui, quel est votre numéro de téléphone principal'
    col_1_14_Avez_vous_un_WhatsApp = models.CharField(max_length=255) # verbose_name='1.14. Avez-vous un WhatsApp'
    col_1_15_Si_Oui_quel_est_votre_numéro_de_téléphone_Whasapp = models.FloatField(null=True,blank=True) # verbose_name='1.15. Si Oui, quel est votre numéro de téléphone Whasapp'
    col_1_16_Avez_vous_une_adresse_email = models.CharField(max_length=255) # verbose_name='1.16. Avez-vous une adresse email'
    col_1_17_Si_oui_quel_est_votre_mail = models.CharField(max_length=255) # verbose_name='1.17. Si oui quel est votre mail'
    col_1_18_Lieu_d_exercice_de_l_activité = models.CharField(max_length=255) # verbose_name='1.18. Lieu d’exercice de l’activité'
    Précisez_le_lieu_de_l_activité = models.CharField(max_length=255) # verbose_name='Précisez le lieu de l'activité'
    col_1_19_Position_GPS_de_l_atelier_Point_GPS = models.CharField(max_length=255) # verbose_name='1.19 Position GPS de l’atelier (Point GPS)'
    _1_19_Position_GPS_de_l_atelier_Point_GPS_latitude = models.FloatField(null=True,blank=True) # verbose_name='_1.19 Position GPS de l’atelier (Point GPS)_latitude'
    _1_19_Position_GPS_de_l_atelier_Point_GPS_longitude = models.FloatField(null=True,blank=True) # verbose_name='_1.19 Position GPS de l’atelier (Point GPS)_longitude'
    _1_19_Position_GPS_de_l_atelier_Point_GPS_altitude = models.FloatField(null=True,blank=True) # verbose_name='_1.19 Position GPS de l’atelier (Point GPS)_altitude'
    _1_19_Position_GPS_de_l_atelier_Point_GPS_precision = models.FloatField(null=True,blank=True) # verbose_name='_1.19 Position GPS de l’atelier (Point GPS)_precision'
    col_2_1_Quelle_est_votre_zone_de_couverture_zone_de_chalandise = models.CharField(max_length=255) # verbose_name='2.1. Quelle est votre zone de couverture (zone de chalandise) ?'   
    col_2_2_Depuis_combien_d_années_exercez_vous_ce_métier = models.CharField(max_length=255) # verbose_name='2.2. Depuis combien d’années exercez-vous ce métier ?'
    col_2_3_Quelle_a_été_la_source_de_financement_au_démarrage_de_v = models.CharField(max_length=255) # verbose_name='2.3. Quelle a été la source de financement au démarrage de votre activité ?'
    Précisez_la_source_de_financement = models.CharField(max_length=255) # verbose_name='Précisez la source de financement'
    col_2_4_Travaillez_vous_avec_d_autres_artisans = models.CharField(max_length=255) # verbose_name='2.4. Travaillez-vous avec d’autres artisans ?'
    col_2_5_Êtes_vous_membre_d_une_association_de_votre_domaine_d_a = models.CharField(max_length=255) # verbose_name='2.5. Êtes-vous membre d'une association de votre domaine d’activité ?'
    col_2_6_Combien_d_heure_par_jour_consacrez_vous_à_votre_activit = models.CharField(max_length=255) # verbose_name='2.6. Combien d’heure par jour consacrez-vous à votre activité'
    col_2_7_Quelle_est_la_plage_horaire_consacrée_à_l_ouverture_et = models.CharField(max_length=255) # verbose_name='2.7 Quelle est la plage horaire consacrée à l’ouverture et à la fermeture de votre activité par jour'
    Précisez_l_heure = models.CharField(max_length=255) # verbose_name='Précisez l'heure'
    col_2_8_A_combien_estimez_vous_le_chiffre_d_affaires_vente_de_v = models.CharField(max_length=255) # verbose_name='2.8 A combien estimez-vous le chiffre d’affaires (vente) de votre activité par mois ?'
    col_2_9_Combien_d_employés_avez_vous = models.CharField(max_length=255) # verbose_name='2.9. Combien d’employés avez-vous ? '
    col_2_10_Êtes_vous_satisfait_des_résultats_actuels_de_votre_act = models.CharField(max_length=255) # verbose_name='2.10. Êtes-vous satisfait des résultats actuels de votre activité ?'
    col_2_11_Quelles_sont_les_difficultés_que_vous_rencontrez_actue = models.CharField(max_length=255) # verbose_name='2.11 Quelles sont les difficultés que vous rencontrez actuellement dans votre activité ?'
    Précisez_les_difficultés = models.CharField(max_length=255) # verbose_name='Précisez les difficultés'
    col_2_13_Avez_vous_un_registre_de_commerce_RC = models.CharField(max_length=255) # verbose_name='2.13. Avez-vous un registre de commerce (RC) ?'
    col_2_14_Payez_vous_des_taxes = models.CharField(max_length=255) # verbose_name='2.14. Payez-vous des taxes ?'
    col_2_15_Si_oui_quel_type_de_taxes_payez_vous = models.CharField(max_length=255) # verbose_name='2.15. Si oui, quel type de taxes payez-vous ?'
    Précisez_le_taxe = models.CharField(max_length=255) # verbose_name='Précisez le taxe'
    col_2_16_Etes_vous_disposés_à_légaliser_votre_activité = models.CharField(max_length=255) # verbose_name='2.16. Etes-vous disposés à légaliser votre activité ?'
    col_2_17_Avez_vous_besoin_d_une_assistance_juridique_pour_des_q = models.CharField(max_length=255) # verbose_name='2.17 Avez-vous besoin d'une assistance juridique pour des questions spécifiques dans votre activité artisanale ?'
    col_2_18_Si_oui_quels_sont_ces_besoins_Plusieurs_réponses_possi = models.CharField(max_length=255) # verbose_name='2.18. Si oui, quels sont ces besoins ? (Plusieurs réponses possibles)'
    col_2_19_Comment_voyez_vous_le_développement_de_votre_activité = models.CharField(max_length=255) # verbose_name='2.19 Comment voyez-vous le développement de votre activité dans 5 ans ?'
    Précisez = models.CharField(max_length=255) # verbose_name='Précisez'
    col_3_Voulez_vous_avoir_des_pages_publicitaires_dédiées_à_votre = models.CharField(max_length=255) # verbose_name='3 Voulez-vous avoir des pages publicitaires dédiées à votre activité ?'
    col_3_1_Souhaiteriez_vous_être_accompagné_d_un_service_numériqu = models.CharField(max_length=255) # verbose_name='3.1 Souhaiteriez-vous être accompagné d’un service numérique à travers le développement d’une application pour la promotion de vos marchandises ?'
    col_3_1_1_Si_Oui_combien_seriez_vous_prêt_à_payer_pour_cette_ap = models.CharField(max_length=255) # verbose_name='3.1.1 Si Oui combien seriez-vous prêt à payer pour cette application ?'
    col_3_2_Quels_objectifs_voulez_vous_atteindre_au_travers_de_cet = models.CharField(max_length=255) # verbose_name='3.2 Quels objectifs voulez-vous atteindre au travers de cette plateforme ?'
    Précisez_l_objectif = models.CharField(max_length=255) # verbose_name='Précisez l'objectif'
    col_3_3_Quels_types_de_contenus_vous_intéresseraient_pour_promo = models.CharField(max_length=255) # verbose_name='3.3 Quels types de contenus vous intéresseraient pour promouvoir votre activité artisanale ? (Plusieurs réponses possibles)'
    Précisez_1 = models.CharField(max_length=255) # verbose_name='Précisez.1'
    col_3_4_Souhaiteriez_vous_être_formé_sur_l_utilisation_des_serv = models.CharField(max_length=255) # verbose_name='3.4 Souhaiteriez-vous être formé sur l’utilisation des services en ligne pour la promotion de vos marchandises ?'
    col_3_4_1_Si_Oui_combien_seriez_vous_prêt_à_payer_pour_cette_fo = models.CharField(max_length=255) # verbose_name='3.4.1 Si Oui combien seriez-vous prêt à payer pour cette formation ?'
    col_3_5_Avez_vous_des_craintes_concernant_l_utilisation_des_ser = models.CharField(max_length=255) # verbose_name='3.5. Avez vous des craintes concernant l'utilisation des services en ligne ?'
    col_3_5_1_Si_oui_pouvez_vous_indiquer_ces_craintes = models.CharField(max_length=255) # verbose_name='3.5.1. Si oui, pouvez-vous indiquer ces craintes ?'
    col_3_5_1_Si_oui_pouvez_vous_indiquer_ces_craintes_1_Anarque = models.FloatField(null=True,blank=True) # verbose_name='3.5.1. Si oui, pouvez-vous indiquer ces craintes ?/1. Anarque '
    col_3_5_1_Si_oui_pouvez_vous_indiquer_ces_craintes_2_Piraterie = models.FloatField(null=True,blank=True) # verbose_name='3.5.1. Si oui, pouvez-vous indiquer ces craintes ?/2. Piraterie '
    col_3_5_1_Si_oui_pouvez_vous_indiquer_ces_craintes_3_Problème_d = models.FloatField(null=True,blank=True) # verbose_name='3.5.1. Si oui, pouvez-vous indiquer ces craintes ?/3. Problème d’accès à internet '
    col_3_5_1_Si_oui_pouvez_vous_indiquer_ces_craintes_4_Confidenti = models.FloatField(null=True,blank=True) # verbose_name='3.5.1. Si oui, pouvez-vous indiquer ces craintes ?/4. Confidentialité des données '
    col_3_5_1_Si_oui_pouvez_vous_indiquer_ces_craintes_5_Difficulté = models.FloatField(null=True,blank=True) # verbose_name='3.5.1. Si oui, pouvez-vous indiquer ces craintes ?/5. Difficultés d’accès à internet '
    col_3_5_1_Si_oui_pouvez_vous_indiquer_ces_craintes_6_Autres_Pré = models.FloatField(null=True,blank=True) # verbose_name='3.5.1. Si oui, pouvez-vous indiquer ces craintes ?/6. Autres(Préciser) '
    Précisez_2 = models.CharField(max_length=255) # verbose_name='Précisez.2'
    col_3_6_Quel_est_selon_vous_l_avantage_d_utiliser_une_plateform = models.CharField(max_length=255) # verbose_name='3.6 Quel est selon vous l’avantage d’utiliser une plateforme de promotion pour vos activités ?'
    Précisez_3 = models.CharField(max_length=255) # verbose_name='Précisez.3'
    col_3_7_Avez_vous_déjà_entendu_parler_de_l_intelligence_artific = models.CharField(max_length=255) # verbose_name='3.7. Avez-vous déjà entendu parler de l’intelligence artificielle ?'
    col_3_7_1_Si_oui_par_quel_moyen_avez_vous_eu_les_informations_s = models.CharField(max_length=255) # verbose_name='3.7.1 Si oui, par quel moyen avez-vous eu les informations sur l’intelligence artificielle ?'
    col_3_8_Avez_vous_déjà_utilisé_l_intelligence_artificielle_dans = models.CharField(max_length=255) # verbose_name='3.8 Avez-vous déjà utilisé l’intelligence artificielle dans le cadre de votre activité ? '
    col_4_Avez_vous_un_compte_sur_un_réseau_social = models.CharField(max_length=255) # verbose_name='4. Avez-vous un compte sur un réseau social ?'
    col_4_1_Si_oui_quel_réseau_social_utilisez_vous_le_plus_pour_fa = models.CharField(max_length=255) # verbose_name='4.1 Si oui, quel réseau social utilisez-vous le plus pour faire la promotion de articles ?'
    Précisez_4 = models.CharField(max_length=255) # verbose_name='Précisez.4'
    col_4_2_Quels_types_de_supports_utilisez_vous_pour_faire_la_pro = models.CharField(max_length=255) # verbose_name='4.2 Quels types de supports utilisez vous pour faire la promotion de vos articles ?'
    Précisez_5 = models.CharField(max_length=255) # verbose_name='Précisez.5'
    col_4_3_Pensez_vous_que_la_promotion_de_vos_marchandises_ou_ser = models.CharField(max_length=255) # verbose_name='4.3 Pensez-vous que la promotion de vos marchandises ou services en ligne pourrait contribuer à faire évoluer votre activité ?'
    col_4_4_Quels_sont_les_moyens_de_paiement_que_vous_utilisez_dan = models.CharField(max_length=255) # verbose_name='4.4 Quels sont les moyens de paiement que vous utilisez dans le cadre de votre activité ?'
    Précisez_6 = models.CharField(max_length=255) # verbose_name='Précisez.6'
    col_4_5_Comment_préférez_vous_recevoir_des_informations_sur_de = models.CharField(max_length=255) # verbose_name='4.5 Comment préférez-vous recevoir des informations sur de nouveaux services ou promotions liés à l'artisanat ?'
    Précisez_7 = models.CharField(max_length=255) # verbose_name='Précisez.7'
    col_4_7_Avez_vous_un_service_de_gestion_de_commandes_de_plainte = models.CharField(max_length=255) # verbose_name='4.7 Avez-vous un service de gestion de commandes, de plaintes et réclamations de vos clients ?'
    col_4_8_Voulez_vous_un_accompagnement_dans_la_gestion_de_comman = models.CharField(max_length=255) # verbose_name='4.8 Voulez-vous un accompagnement dans la gestion de commandes, de plaintes et de réclamations de vos clients via une plateforme ?'
    col_4_9_Quels_types_d_accompagnement_souhaiteriez_vous = models.CharField(max_length=255) # verbose_name='4.9 Quels types d’accompagnement souhaiteriez-vous ?'
    col_4_9_Quels_types_d_accompagnement_souhaiteriez_vous_1_Accuei = models.FloatField(null=True,blank=True) # verbose_name='4.9 Quels types d’accompagnement souhaiteriez-vous ?/1. Accueil de la réclamation '
    col_4_9_Quels_types_d_accompagnement_souhaiteriez_vous_2_Evalua = models.FloatField(null=True,blank=True) # verbose_name='4.9 Quels types d’accompagnement souhaiteriez-vous ?/2. Evaluation de la réclamation '
    col_4_9_Quels_types_d_accompagnement_souhaiteriez_vous_3_Commun = models.FloatField(null=True,blank=True) # verbose_name='4.9 Quels types d’accompagnement souhaiteriez-vous ?/3. Communication avec la clientèle'
    col_4_9_Quels_types_d_accompagnement_souhaiteriez_vous_4_Répara = models.FloatField(null=True,blank=True) # verbose_name='4.9 Quels types d’accompagnement souhaiteriez-vous ?/4. Réparation ou remplacement d’un articles'
    col_4_9_Quels_types_d_accompagnement_souhaiteriez_vous_5_Autres = models.FloatField(null=True,blank=True) # verbose_name='4.9 Quels types d’accompagnement souhaiteriez-vous ?/5. Autres (Préciser) '
    col_4_10_Combien_êtes_vous_prêt_à_payer_pour_ces_appuis = models.CharField(max_length=255) # verbose_name='4.10 Combien êtes-vous prêt à payer pour ces appuis ?'
    col_4_11_Quels_sont_vos_différentes_catégories_de_clients = models.CharField(max_length=255) # verbose_name='4.11 Quels sont vos différentes catégories de clients ?'
    col_4_11_Quels_sont_vos_différentes_catégories_de_clients_1_Par = models.FloatField(null=True,blank=True) # verbose_name='4.11 Quels sont vos différentes catégories de clients ?/1. Particuliers '
    col_4_11_Quels_sont_vos_différentes_catégories_de_clients_2_Soc = models.FloatField(null=True,blank=True) # verbose_name='4.11 Quels sont vos différentes catégories de clients ?/2. Société privée '
    col_4_11_Quels_sont_vos_différentes_catégories_de_clients_3_Fon = models.FloatField(null=True,blank=True) # verbose_name='4.11 Quels sont vos différentes catégories de clients ?/3. Fonction publique'
    col_4_11_Quels_sont_vos_différentes_catégories_de_clients_4_Aut = models.FloatField(null=True,blank=True) # verbose_name='4.11 Quels sont vos différentes catégories de clients ?/4. Autres (Préciser) '
    Précisez_8 = models.CharField(max_length=255) # verbose_name='Précisez.8'
    col_4_12_Avez_vous_déjà_réalisé_des_études_de_marché_pour_compr = models.CharField(max_length=255) # verbose_name='4.12 Avez-vous déjà réalisé des études de marché pour comprendre aux besoins de vos clients ?'
    col_4_13_Avez_vous_un_service_de_livraison = models.CharField(max_length=255) # verbose_name='4.13 Avez-vous un service de livraison ?'
    col_4_14_Si_oui_quel_moyen_utilisez_vous_pour_vos_livraisons = models.CharField(max_length=255) # verbose_name='4.14. Si oui, quel moyen utilisez-vous pour vos livraisons'
    col_4_14_Si_oui_quel_moyen_utilisez_vous_pour_vos_livraisons_1 = models.FloatField(null=True,blank=True) # verbose_name='4.14. Si oui, quel moyen utilisez-vous pour vos livraisons/1. Livraison en magasin/boutique '
    col_4_14_Si_oui_quel_moyen_utilisez_vous_pour_vos_livraisons_2 = models.FloatField(null=True,blank=True) # verbose_name='4.14. Si oui, quel moyen utilisez-vous pour vos livraisons/2. Livraison par courrier '
    col_4_14_Si_oui_quel_moyen_utilisez_vous_pour_vos_livraisons_3 = models.FloatField(null=True,blank=True) # verbose_name='4.14. Si oui, quel moyen utilisez-vous pour vos livraisons/3. Livraison à domicile'
    col_4_14_Si_oui_quel_moyen_utilisez_vous_pour_vos_livraisons_4 = models.FloatField(null=True,blank=True) # verbose_name='4.14. Si oui, quel moyen utilisez-vous pour vos livraisons/4. Livraison en centre de distribution'
    col_4_14_Si_oui_quel_moyen_utilisez_vous_pour_vos_livraisons_5 = models.FloatField(null=True,blank=True) # verbose_name='4.14. Si oui, quel moyen utilisez-vous pour vos livraisons/5. Autres (Préciser) '
    Précisez_9 = models.CharField(max_length=255) # verbose_name='Précisez.9'
    col_4_15_Comment_se_font_les_livraisons = models.CharField(max_length=255) # verbose_name='4.15 Comment se font les livraisons ?'
    col_4_15_Comment_se_font_les_livraisons_1_Déplacement_à_pied = models.FloatField(null=True,blank=True) # verbose_name='4.15 Comment se font les livraisons ?/1. Déplacement à pied '
    col_4_15_Comment_se_font_les_livraisons_2_Automobile = models.FloatField(null=True,blank=True) # verbose_name='4.15 Comment se font les livraisons ?/2. Automobile '
    col_4_15_Comment_se_font_les_livraisons_3_Moto = models.FloatField(null=True,blank=True) # verbose_name='4.15 Comment se font les livraisons ?/3. Moto'
    col_4_15_Comment_se_font_les_livraisons_4_Camion = models.FloatField(null=True,blank=True) # verbose_name='4.15 Comment se font les livraisons ?/4. Camion '
    col_4_15_Comment_se_font_les_livraisons_5_Bateau = models.FloatField(null=True,blank=True) # verbose_name='4.15 Comment se font les livraisons ?/5. Bateau '
    col_4_15_Comment_se_font_les_livraisons_6_Autres_Préciser = models.FloatField(null=True,blank=True) # verbose_name='4.15 Comment se font les livraisons ?/6. Autres (Préciser) '
    Précisez_10 = models.CharField(max_length=255) # verbose_name='Précisez.10'
    col_14_16_FIN_DE_L_ENQUETE = models.CharField(max_length=255) # verbose_name='14.16. FIN DE L’ENQUETE'
    col_1_CIVILITÉ = models.FloatField(null=True,blank=True) # verbose_name='1- CIVILITÉ'
    CIVILITÉ = models.FloatField(null=True,blank=True) # verbose_name='CIVILITÉ'
    col_2_NOM_ET_PRÉNOM_S = models.FloatField(null=True,blank=True) # verbose_name='2- NOM ET PRÉNOM(S)'
    NOM_ET_PRÉNOM_S = models.FloatField(null=True,blank=True) # verbose_name='NOM ET PRÉNOM(S)'
    col_3_Quelle_est_votre_tranche_d_âge = models.FloatField(null=True,blank=True) # verbose_name='3- Quelle est votre tranche d'âge ?'
    col_3_Quelle_est_votre_tranche_d_âge_3_1_Moins_de_25_ans = models.FloatField(null=True,blank=True) # verbose_name='3- Quelle est votre tranche d'âge ?/3.1. Moins de 25 ans'
    col_3_Quelle_est_votre_tranche_d_âge_3_2_25_35m4_ans = models.FloatField(null=True,blank=True) # verbose_name='3- Quelle est votre tranche d'âge ?/3.2. 25 - 35m4 ans'
    col_3_Quelle_est_votre_tranche_d_âge_3_3_35_44_ans = models.FloatField(null=True,blank=True) # verbose_name='3- Quelle est votre tranche d'âge ?/3.3. 35 - 44 ans'
    col_3_Quelle_est_votre_tranche_d_âge_3_4_44_à_55_ans = models.FloatField(null=True,blank=True) # verbose_name='3- Quelle est votre tranche d'âge ?/3.4. 44 à 55 ans'
    col_3_Quelle_est_votre_tranche_d_âge_3_5_Plus_de_55_ans = models.FloatField(null=True,blank=True) # verbose_name='3- Quelle est votre tranche d'âge ?/3.5. Plus de 55 ans'
    col_3_Quelle_est_âge_avez_vous = models.FloatField(null=True,blank=True) # verbose_name='3- Quelle est âge avez-vous ?'
    col_3_Quelle_est_âge_avez_vous_18_25_ans = models.FloatField(null=True,blank=True) # verbose_name='3- Quelle est âge avez-vous ?/18 - 25 ans'
    col_3_Quelle_est_âge_avez_vous_25_35_ans = models.FloatField(null=True,blank=True) # verbose_name='3- Quelle est âge avez-vous ?/25 - 35 ans'
    col_3_Quelle_est_âge_avez_vous_35_45_ans = models.FloatField(null=True,blank=True) # verbose_name='3- Quelle est âge avez-vous ?/35 - 45 ans'
    col_3_Quelle_est_âge_avez_vous_45_ans_et_plus = models.FloatField(null=True,blank=True) # verbose_name='3- Quelle est âge avez-vous ?/45 ans et plus '
    Quelle_est_âge_avez_vous = models.FloatField(null=True,blank=True) # verbose_name='Quelle est âge avez-vous ?'
    Quelle_est_âge_avez_vous_18_25_ans = models.FloatField(null=True,blank=True) # verbose_name='Quelle est âge avez-vous ?/18 - 25 ans'
    Quelle_est_âge_avez_vous_25_35_ans = models.FloatField(null=True,blank=True) # verbose_name='Quelle est âge avez-vous ?/25 - 35 ans'
    Quelle_est_âge_avez_vous_35_45_ans = models.FloatField(null=True,blank=True) # verbose_name='Quelle est âge avez-vous ?/35 - 45 ans'
    Quelle_est_âge_avez_vous_45_ans_et_plus = models.FloatField(null=True,blank=True) # verbose_name='Quelle est âge avez-vous ?/45 ans et plus '
    col_4_De_quel_pays_êtes_vous = models.FloatField(null=True,blank=True) # verbose_name='4- De quel pays êtes-vous ?'
    col_4_De_quel_pays_êtes_vous_4_1_Côte_d_Ivoire = models.FloatField(null=True,blank=True) # verbose_name='4- De quel pays êtes-vous ?/4.1. Côte d'Ivoire'
    col_4_De_quel_pays_êtes_vous_4_2_CEDEAO = models.FloatField(null=True,blank=True) # verbose_name='4- De quel pays êtes-vous ?/4.2. CEDEAO '
    col_4_De_quel_pays_êtes_vous_4_3_Hors_CEDEAO_tous_les_pays = models.FloatField(null=True,blank=True) # verbose_name='4- De quel pays êtes-vous ?/4.3. Hors CEDEAO (tous les pays)'
    De_quel_pays_êtes_vous = models.FloatField(null=True,blank=True) # verbose_name='De quel pays êtes-vous ?'
    De_quel_pays_êtes_vous_Côte_d_Ivoire = models.FloatField(null=True,blank=True) # verbose_name='De quel pays êtes-vous ?/Côte d'Ivoire'
    De_quel_pays_êtes_vous_Autre = models.FloatField(null=True,blank=True) # verbose_name='De quel pays êtes-vous ?/Autre'
    O_5_COMMUNE_VILLAGE_DE_L_ENQUETE_1 = models.CharField(max_length=255) # verbose_name='O.5. COMMUNE / VILLAGE DE L’ENQUETE .1'
    col_5_La_ville = models.FloatField(null=True,blank=True) # verbose_name='5- La ville'
    col_5_La_ville_5_1_Abidjan = models.FloatField(null=True,blank=True) # verbose_name='5- La ville/5.1. Abidjan '
    col_5_La_ville_5_2_Yamoussoukro = models.FloatField(null=True,blank=True) # verbose_name='5- La ville/5 2. Yamoussoukro'
    col_5_La_ville_5_3_Bouaké = models.FloatField(null=True,blank=True) # verbose_name='5- La ville/5.3. Bouaké'
    col_5_La_ville_5_4_San_Pédro = models.FloatField(null=True,blank=True) # verbose_name='5- La ville/5.4. San-Pédro'
    col_5_La_ville_5_5_Korhogo = models.FloatField(null=True,blank=True) # verbose_name='5- La ville/5.5. Korhogo'
    col_5_La_ville_5_6_Autre_préciser = models.FloatField(null=True,blank=True) # verbose_name='5- La ville/5.6. Autre (préciser)'
    col_5_La_ville_quartier = models.FloatField(null=True,blank=True) # verbose_name='5- La ville/quartier'
    col_5_La_ville_quartier_Abidjan = models.FloatField(null=True,blank=True) # verbose_name='5- La ville/quartier/Abidjan '
    col_5_La_ville_quartier_Yamoussoukro = models.FloatField(null=True,blank=True) # verbose_name='5- La ville/quartier/Yamoussoukro'
    col_5_La_ville_quartier_Bouaké = models.FloatField(null=True,blank=True) # verbose_name='5- La ville/quartier/Bouaké'
    col_5_La_ville_quartier_San_Pédro = models.FloatField(null=True,blank=True) # verbose_name='5- La ville/quartier/San-Pédro'
    col_5_La_ville_quartier_Korhogo = models.FloatField(null=True,blank=True) # verbose_name='5- La ville/quartier/Korhogo'
    col_5_La_ville_quartier_Autre_préciser = models.FloatField(null=True,blank=True) # verbose_name='5- La ville/quartier/Autre (préciser)'
    La_ville_quartier = models.FloatField(null=True,blank=True) # verbose_name='La ville/quartier'
    La_ville_quartier_Abidjan = models.FloatField(null=True,blank=True) # verbose_name='La ville/quartier/Abidjan '
    La_ville_quartier_Yamoussoukro = models.FloatField(null=True,blank=True) # verbose_name='La ville/quartier/Yamoussoukro'
    La_ville_quartier_Bouaké = models.FloatField(null=True,blank=True) # verbose_name='La ville/quartier/Bouaké'
    La_ville_quartier_San_Pédro = models.FloatField(null=True,blank=True) # verbose_name='La ville/quartier/San-Pédro'
    La_ville_quartier_Korhogo = models.FloatField(null=True,blank=True) # verbose_name='La ville/quartier/Korhogo'
    La_ville_quartier_Autre_préciser = models.FloatField(null=True,blank=True) # verbose_name='La ville/quartier/Autre (préciser)'
    col_6_Avez_vous_un_numéro_de_téléphone = models.FloatField(null=True,blank=True) # verbose_name='6- Avez-vous un numéro de téléphone ?'
    col_6_Avez_vous_un_numéro_de_téléphone_OUI = models.FloatField(null=True,blank=True) # verbose_name='6- Avez-vous un numéro de téléphone ?/OUI'
    col_6_Avez_vous_un_numéro_de_téléphone_6_2_NON = models.FloatField(null=True,blank=True) # verbose_name='6- Avez-vous un numéro de téléphone ?/6.2. NON'
    col_6_Avez_vous_un_numéro_de_téléphone_6_1_OUI = models.FloatField(null=True,blank=True) # verbose_name='6- Avez-vous un numéro de téléphone ?/6.1. OUI'
    Avez_vous_un_numéro_de_téléphone = models.FloatField(null=True,blank=True) # verbose_name='Avez-vous un numéro de téléphone ?'
    Avez_vous_un_numéro_de_téléphone_OUI = models.FloatField(null=True,blank=True) # verbose_name='Avez-vous un numéro de téléphone ?/OUI'
    Avez_vous_un_numéro_de_téléphone_NON = models.FloatField(null=True,blank=True) # verbose_name='Avez-vous un numéro de téléphone ?/NON'
    Si_oui_quel_est_votre_numéro_de_téléphone_principal = models.FloatField(null=True,blank=True) # verbose_name='Si oui, quel est votre numéro de téléphone principal ?'
    col_6_1_Quel_est_votre_numéro_de_téléphone_principal = models.FloatField(null=True,blank=True) # verbose_name='6-1- Quel est votre numéro de téléphone principal ?'
    Quel_est_votre_numéro_de_téléphone_principal = models.FloatField(null=True,blank=True) # verbose_name='Quel est votre numéro de téléphone principal ?'
    col_7_Quel_métier_exercez_vous = models.FloatField(null=True,blank=True) # verbose_name='7- Quel métier exercez-vous ?'
    col_7_Quel_métier_exercez_vous_7_1_La_mécanique = models.FloatField(null=True,blank=True) # verbose_name='7- Quel métier exercez-vous ?/7.1. La mécanique'
    col_7_Quel_métier_exercez_vous_7_2_La_menuiserie = models.FloatField(null=True,blank=True) # verbose_name='7- Quel métier exercez-vous ?/7.2. La menuiserie'
    col_7_Quel_métier_exercez_vous_7_3_La_maçonnerie = models.FloatField(null=True,blank=True) # verbose_name='7- Quel métier exercez-vous ?/7.3. La maçonnerie'
    col_7_Quel_métier_exercez_vous_7_4_La_couture = models.FloatField(null=True,blank=True) # verbose_name='7- Quel métier exercez-vous ?/7.4. La couture'
    col_7_Quel_métier_exercez_vous_7_5_La_tapisserie = models.FloatField(null=True,blank=True) # verbose_name='7- Quel métier exercez-vous ?/7.5. La tapisserie'
    col_7_Quel_métier_exercez_vous_7_6_La_ferronnerie = models.FloatField(null=True,blank=True) # verbose_name='7- Quel métier exercez-vous ?/7.6. La ferronnerie '
    col_7_Quel_métier_exercez_vous_7_7_La_coiffure = models.FloatField(null=True,blank=True) # verbose_name='7- Quel métier exercez-vous ?/7.7. La coiffure '
    col_7_Quel_métier_exercez_vous_7_8_L_électronique_réparateur_TV = models.FloatField(null=True,blank=True) # verbose_name='7- Quel métier exercez-vous ?/7.8. L'électronique (réparateur TV, portable, etc)'
    col_7_Quel_métier_exercez_vous_7_9_La_briqueterie = models.FloatField(null=True,blank=True) # verbose_name='7- Quel métier exercez-vous ?/7.9. La briqueterie'
    col_7_Quel_métier_exercez_vous_7_10_La_charpenterie = models.FloatField(null=True,blank=True) # verbose_name='7- Quel métier exercez-vous ?/7.10. La charpenterie '
    col_7_Quel_métier_exercez_vous_7_11_Spécialiste_en_froid = models.FloatField(null=True,blank=True) # verbose_name='7- Quel métier exercez-vous ?/7.11. Spécialiste en froid '
    col_7_Quel_métier_exercez_vous_7_12_La_bijouterie = models.FloatField(null=True,blank=True) # verbose_name='7- Quel métier exercez-vous ?/7.12. La bijouterie '
    col_7_Quel_métier_exercez_vous_7_13_La_boucherie = models.FloatField(null=True,blank=True) # verbose_name='7- Quel métier exercez-vous ?/7.13. La boucherie '
    col_7_Quel_métier_exercez_vous_7_14_Vente_de_marchandises_diver = models.FloatField(null=True,blank=True) # verbose_name='7- Quel métier exercez-vous ?/7.14. Vente de marchandises diverses '
    col_7_Quel_métier_exercez_vous_7_15_La_restauration = models.FloatField(null=True,blank=True) # verbose_name='7- Quel métier exercez-vous ?/7.15. La restauration'
    col_7_Quel_métier_exercez_vous_7_16_La_vitrerie = models.FloatField(null=True,blank=True) # verbose_name='7- Quel métier exercez-vous ?/7.16. La vitrerie '
    col_7_Quel_métier_exercez_vous_7_17_Autre = models.FloatField(null=True,blank=True) # verbose_name='7- Quel métier exercez-vous ?/7.17. Autre '
    Quel_métier_exercez_vous = models.FloatField(null=True,blank=True) # verbose_name='Quel métier exercez-vous ?'
    col_8_Depuis_combien_d_années_exercez_vous_ce_métier = models.FloatField(null=True,blank=True) # verbose_name='8- Depuis combien d'années exercez-vous ce métier ?'
    col_8_Depuis_combien_d_années_exercez_vous_ce_métier_8_1_Moins = models.FloatField(null=True,blank=True) # verbose_name='8- Depuis combien d'années exercez-vous ce métier ?/8.1. Moins d'un an'
    col_8_Depuis_combien_d_années_exercez_vous_ce_métier_8_2_Entre = models.FloatField(null=True,blank=True) # verbose_name='8- Depuis combien d'années exercez-vous ce métier ?/8.2. Entre 1 et 4 ans'
    col_8_Depuis_combien_d_années_exercez_vous_ce_métier_8_3_Plus_d = models.FloatField(null=True,blank=True) # verbose_name='8- Depuis combien d'années exercez-vous ce métier ?/8.3. Plus de 5 ans'
    Depuis_combien_d_années_exercez_vous_ce_métier = models.FloatField(null=True,blank=True) # verbose_name='Depuis combien d'années exercez-vous ce métier ?'
    Depuis_combien_d_années_exercez_vous_ce_métier_Moins_d_un_an = models.FloatField(null=True,blank=True) # verbose_name='Depuis combien d'années exercez-vous ce métier ?/Moins d'un an'
    Depuis_combien_d_années_exercez_vous_ce_métier_Entre_1_et_4_ans = models.FloatField(null=True,blank=True) # verbose_name='Depuis combien d'années exercez-vous ce métier ?/Entre 1 et 4 ans'
    Depuis_combien_d_années_exercez_vous_ce_métier_Plus_de_5_ans = models.FloatField(null=True,blank=True) # verbose_name='Depuis combien d'années exercez-vous ce métier ?/Plus de 5 ans'
    O_8_FIN_DE_L_ENQUETE = models.CharField(max_length=255) # verbose_name='O.8. FIN DE L’ENQUETE         '
    col_9_Pensez_vous_que_votre_activité_contribue_au_développement = models.FloatField(null=True,blank=True) # verbose_name='9. Pensez-vous que votre activité contribue au développement socioéconomique de la Côte d'Ivoire ?'
    col_9_Êtes_vous_satisfait_des_résultats_actuels_de_votre_activi = models.FloatField(null=True,blank=True) # verbose_name='9- Êtes-vous satisfait des résultats actuels de votre activité ?'
    Pensez_vous_que_votre_activité_contribue_au_développement_socio = models.FloatField(null=True,blank=True) # verbose_name='Pensez-vous que votre activité contribue au développement socioéconomique de la Côte d'Ivoire ?'
    col_1_3_Quel_est_le_type_d_activité_exercé_1 = models.CharField(max_length=255) # verbose_name='1.3 Quel est le type d'activité exercé ?.1'
    col_10_Êtes_vous_satisfait_des_résultats_actuels_de_votre_activ = models.FloatField(null=True,blank=True) # verbose_name='10- Êtes-vous satisfait des résultats actuels de votre activité ?'
    col_10_Quelle_est_la_source_de_financement_qui_a_permis_le_déma = models.FloatField(null=True,blank=True) # verbose_name='10- Quelle est la source de financement qui a permis le démarrage de votre activité ?'
    Êtes_vous_satisfait_des_résultats_actuels_de_votre_activité = models.FloatField(null=True,blank=True) # verbose_name='Êtes-vous satisfait des résultats actuels de votre activité ?'
    col_11_Quelles_sont_les_difficultés_que_vous_rencontrez_actuell = models.FloatField(null=True,blank=True) # verbose_name='11- Quelles sont les difficultés que vous rencontrez actuellement dans votre activité ?'
    col_11_Quelles_sont_les_difficultés_que_vous_avez_rencontrées_l = models.FloatField(null=True,blank=True) # verbose_name='11- Quelles sont les difficultés que vous avez rencontrées les premiers mois suivant le démarrage de votre activité ?'
    col_11_Comment_évaluez_vous_le_développement_actuel_de_votre_ac = models.FloatField(null=True,blank=True) # verbose_name='11- Comment évaluez-vous le développement actuel de votre activité ?'
    Comment_évaluez_vous_le_développement_actuel_de_votre_activité = models.FloatField(null=True,blank=True) # verbose_name='Comment évaluez-vous le développement actuel de votre activité ?'
    col_12_Comment_voyez_vous_le_développement_de_votre_activité_da = models.FloatField(null=True,blank=True) # verbose_name='12- Comment voyez-vous le développement de votre activité dans les années à venir ?'
    col_12_Combien_peut_vous_rapporter_votre_activité_par_mois = models.FloatField(null=True,blank=True) # verbose_name='12- Combien peut vous rapporter votre activité par mois ?'
    col_12_Combien_peut_vous_rapporter_votre_activité_par_mois_Moin = models.FloatField(null=True,blank=True) # verbose_name='12- Combien peut vous rapporter votre activité par mois ?/Moins de 50.000 FCFA '
    col_12_Combien_peut_vous_rapporter_votre_activité_par_mois_Entr = models.FloatField(null=True,blank=True) # verbose_name='12- Combien peut vous rapporter votre activité par mois ?/Entre 50.000 FCFA et 100.000 FCFA '
    col_12_Combien_peut_vous_rapporter_votre_activité_par_mois_Plus = models.FloatField(null=True,blank=True) # verbose_name='12- Combien peut vous rapporter votre activité par mois ?/Plus de 200.000 FCFA '
    Comment_voyez_vous_votre_activité_dans_les_années_à_venir = models.FloatField(null=True,blank=True) # verbose_name='Comment voyez-vous votre activité dans les années à venir ?'
    Comment_voyez_vous_votre_activité_dans_les_années_à_venir_Une_e = models.FloatField(null=True,blank=True) # verbose_name='Comment voyez-vous votre activité dans les années à venir ?/Une entreprise prospère et Une entreprise légalement constituée'
    Comment_voyez_vous_votre_activité_dans_les_années_à_venir_Le_pr = models.FloatField(null=True,blank=True) # verbose_name='Comment voyez-vous votre activité dans les années à venir ?/Le premier choix des populations'
    Comment_voyez_vous_votre_activité_dans_les_années_à_venir_Augme = models.FloatField(null=True,blank=True) # verbose_name='Comment voyez-vous votre activité dans les années à venir ?/Augmentation de la production'
    col_13_Quelle_est_la_source_de_financement_qui_a_permis_le_déma = models.FloatField(null=True,blank=True) # verbose_name='13- Quelle est la source de financement qui a permis le démarrage de votre activité ?'
    col_13_Utilisez_vous_internet_pour_la_promotion_de_votre_activi = models.FloatField(null=True,blank=True) # verbose_name='13- Utilisez-vous internet pour la promotion de votre activité ?'
    Quelle_est_la_source_de_financement_qui_a_permis_le_démarrage_d = models.FloatField(null=True,blank=True) # verbose_name='Quelle est la source de financement qui a permis le démarrage de votre activité ?'
    col_14_Quelles_sont_les_difficultés_que_vous_avez_rencontrées_l = models.FloatField(null=True,blank=True) # verbose_name='14- Quelles sont les difficultés que vous avez rencontrées les premiers mois suivant le démarrage de votre activité ?'
    col_14_Avez_vous_au_moins_un_compte_sur_un_réseau_social = models.FloatField(null=True,blank=True) # verbose_name='14- Avez-vous au moins un compte sur un réseau social ?'
    col_14_Avez_vous_au_moins_un_compte_sur_un_réseau_social_OUI = models.FloatField(null=True,blank=True) # verbose_name='14- Avez-vous au moins un compte sur un réseau social ?/OUI'
    col_14_Avez_vous_au_moins_un_compte_sur_un_réseau_social_NON = models.FloatField(null=True,blank=True) # verbose_name='14- Avez-vous au moins un compte sur un réseau social ?/NON'
    col_13_Quelles_sont_les_difficultés_que_vous_avez_rencontrées_l = models.FloatField(null=True,blank=True) # verbose_name='13- Quelles sont les difficultés que vous avez rencontrées les premiers mois suivant le démarrage de votre activité ?'
    Quelles_sont_les_difficultés_que_vous_avez_rencontré_les_premie = models.FloatField(null=True,blank=True) # verbose_name='Quelles sont les difficultés que vous avez rencontré les premiers mois suivant le démarrage de votre activité ?'
    col_15_Combien_peut_vous_rapporter_votre_activité_par_mois = models.FloatField(null=True,blank=True) # verbose_name='15- Combien peut vous rapporter votre activité par mois ?'
    col_15_Si_oui_quel_réseau_social_utilisez_vous_le_plus = models.FloatField(null=True,blank=True) # verbose_name='15- Si oui, quel réseau social utilisez-vous le plus ?'
    col_15_Si_oui_quel_réseau_social_utilisez_vous_le_plus_Facebook = models.FloatField(null=True,blank=True) # verbose_name='15- Si oui, quel réseau social utilisez-vous le plus ?/Facebook'
    col_15_Si_oui_quel_réseau_social_utilisez_vous_le_plus_WhatsApp = models.FloatField(null=True,blank=True) # verbose_name='15- Si oui, quel réseau social utilisez-vous le plus ?/WhatsApp'
    col_15_Si_oui_quel_réseau_social_utilisez_vous_le_plus_X_Twitte = models.FloatField(null=True,blank=True) # verbose_name='15- Si oui, quel réseau social utilisez-vous le plus ?/X (Twitter)'
    col_15_Si_oui_quel_réseau_social_utilisez_vous_le_plus_Instagra = models.FloatField(null=True,blank=True) # verbose_name='15- Si oui, quel réseau social utilisez-vous le plus ?/Instagram'
    col_15_Si_oui_quel_réseau_social_utilisez_vous_le_plus_Autre = models.FloatField(null=True,blank=True) # verbose_name='15- Si oui, quel réseau social utilisez-vous le plus ?/Autre'
    col_14_Combien_peut_vous_rapporter_votre_activité_par_mois = models.FloatField(null=True,blank=True) # verbose_name='14- Combien peut vous rapporter votre activité par mois ?'
    col_14_Combien_peut_vous_rapporter_votre_activité_par_mois_Moin = models.FloatField(null=True,blank=True) # verbose_name='14- Combien peut vous rapporter votre activité par mois ?/Moins de 50.000 FCFA '
    col_14_Combien_peut_vous_rapporter_votre_activité_par_mois_Entr = models.FloatField(null=True,blank=True) # verbose_name='14- Combien peut vous rapporter votre activité par mois ?/Entre 50.000 FCFA et 100.000 FCFA '
    col_14_Combien_peut_vous_rapporter_votre_activité_par_mois_Plus = models.FloatField(null=True,blank=True) # verbose_name='14- Combien peut vous rapporter votre activité par mois ?/Plus de 200.000 FCFA '
    Combien_peut_vous_rapporter_votre_activité_par_mois = models.FloatField(null=True,blank=True) # verbose_name='Combien peut vous rapporter votre activité par mois ?'
    Combien_peut_vous_rapporter_votre_activité_par_mois_Moins_de_50 = models.FloatField(null=True,blank=True) # verbose_name='Combien peut vous rapporter votre activité par mois ?/Moins de 50.000 FCFA '
    Combien_peut_vous_rapporter_votre_activité_par_mois_Entre_50_00 = models.FloatField(null=True,blank=True) # verbose_name='Combien peut vous rapporter votre activité par mois ?/Entre 50.000 FCFA et 100.000 FCFA '
    Combien_peut_vous_rapporter_votre_activité_par_mois_Entre_100_0 = models.FloatField(null=True,blank=True) # verbose_name='Combien peut vous rapporter votre activité par mois ?/Entre 100.000 FCFA et 200.000 FCFA '
    Combien_peut_vous_rapporter_votre_activité_par_mois_Plus_de_200 = models.FloatField(null=True,blank=True) # verbose_name='Combien peut vous rapporter votre activité par mois ?/Plus de 200.000 FCFA '
    col_1_9_De_quel_pays_êtes_vous_originaire_1 = models.CharField(max_length=255) # verbose_name='1.9. De quel pays êtes-vous originaire ?.1'
    col_16_Payez_vous_des_taxes = models.FloatField(null=True,blank=True) # verbose_name='16- Payez-vous des taxes ?'
    col_16_Payez_vous_des_taxes_16_1_OUI = models.FloatField(null=True,blank=True) # verbose_name='16- Payez-vous des taxes ?/16.1. OUI'
    col_16_Payez_vous_des_taxes_16_1_NON = models.FloatField(null=True,blank=True) # verbose_name='16- Payez-vous des taxes ?/16.1. .NON'
    col_16_Pensez_vous_que_la_promotion_de_vos_marchandises_en_lign = models.FloatField(null=True,blank=True) # verbose_name='16- Pensez-vous que la promotion de vos marchandises en ligne ou services pourrait contribuer à faire évoluer votre activité?'
    col_15_Combien_de_clients_pourriez_vous_avoir_par_mois = models.FloatField(null=True,blank=True) # verbose_name='15- Combien de clients pourriez-vous avoir par mois ?'
    col_15_Combien_de_clients_pourriez_vous_avoir_par_mois_Moins_de = models.FloatField(null=True,blank=True) # verbose_name='15- Combien de clients pourriez-vous avoir par mois ?/Moins de 10 clients'
    col_15_Combien_de_clients_pourriez_vous_avoir_par_mois_Entre_10 = models.FloatField(null=True,blank=True) # verbose_name='15- Combien de clients pourriez-vous avoir par mois ?/Entre 10 et 25 clients '
    col_15_Combien_de_clients_pourriez_vous_avoir_par_mois_Plus_de = models.FloatField(null=True,blank=True) # verbose_name='15- Combien de clients pourriez-vous avoir par mois ?/Plus de 25 clients '
    Combien_de_clients_pourriez_vous_avoir_par_mois = models.FloatField(null=True,blank=True) # verbose_name='Combien de clients pourriez-vous avoir par mois ?'
    Combien_de_clients_pourriez_vous_avoir_par_mois_Moins_de_10_cli = models.FloatField(null=True,blank=True) # verbose_name='Combien de clients pourriez-vous avoir par mois ?/Moins de 10 clients'
    Combien_de_clients_pourriez_vous_avoir_par_mois_Entre_10_et_25 = models.FloatField(null=True,blank=True) # verbose_name='Combien de clients pourriez-vous avoir par mois ?/Entre 10 et 25 clients '
    Combien_de_clients_pourriez_vous_avoir_par_mois_Plus_de_25_clie = models.FloatField(null=True,blank=True) # verbose_name='Combien de clients pourriez-vous avoir par mois ?/Plus de 25 clients '
    Si_oui_quel_type_de_taxe_payez_vous = models.FloatField(null=True,blank=True) # verbose_name='Si oui, quel type de taxe payez-vous? '
    Si_oui_quel_type_de_taxe_payez_vous_a_Taxe_communale = models.FloatField(null=True,blank=True) # verbose_name='Si oui, quel type de taxe payez-vous? /a- Taxe communale '
    Si_oui_quel_type_de_taxe_payez_vous_b_Patente = models.FloatField(null=True,blank=True) # verbose_name='Si oui, quel type de taxe payez-vous? /b- Patente '
    Si_oui_quel_type_de_taxe_payez_vous_c_TVA = models.FloatField(null=True,blank=True) # verbose_name='Si oui, quel type de taxe payez-vous? /c- TVA'
    col_17_Souhaiteriez_vous_être_formé_sur_l_utilisation_des_servi = models.FloatField(null=True,blank=True) # verbose_name='17-  Souhaiteriez vous être formé sur l'utilisation des services en ligne pour la promotion de vos marchandises ?'
    col_16_Utilisez_vous_internet_pour_la_promotion_de_votre_activi = models.FloatField(null=True,blank=True) # verbose_name='16- Utilisez-vous internet pour la promotion de votre activité ?'
    Utilisez_vous_internet_pour_la_promotion_de_votre_activité = models.FloatField(null=True,blank=True) # verbose_name='Utilisez-vous internet pour la promotion de votre activité ?'
    Utilisez_vous_internet_pour_la_promotion_de_votre_activité_OUI = models.FloatField(null=True,blank=True) # verbose_name='Utilisez-vous internet pour la promotion de votre activité ?/OUI'
    Utilisez_vous_internet_pour_la_promotion_de_votre_activité_Non = models.FloatField(null=True,blank=True) # verbose_name='Utilisez-vous internet pour la promotion de votre activité ?/Non'
    col_17_Utilisez_vous_internet_pour_la_promotion_de_votre_activi = models.FloatField(null=True,blank=True) # verbose_name='17- Utilisez-vous internet pour la promotion de votre activité ?'
    col_18_Combien_seriez_vous_prêt_à_dépenser_pour_votre_formation = models.FloatField(null=True,blank=True) # verbose_name='18-  Combien seriez-vous prêt à dépenser pour votre formation sur le digital ?'
    col_17_Avez_vous_au_moins_un_compte_sur_un_réseau_social = models.FloatField(null=True,blank=True) # verbose_name='17- Avez-vous au moins un compte sur un réseau social ?'
    col_17_Avez_vous_au_moins_un_compte_sur_un_réseau_social_OUI = models.FloatField(null=True,blank=True) # verbose_name='17- Avez-vous au moins un compte sur un réseau social ?/OUI'
    col_17_Avez_vous_au_moins_un_compte_sur_un_réseau_social_NON = models.FloatField(null=True,blank=True) # verbose_name='17- Avez-vous au moins un compte sur un réseau social ?/NON'
    Avez_vous_au_moins_un_compte_sur_un_réseau_social = models.FloatField(null=True,blank=True) # verbose_name='Avez-vous au moins un compte sur un réseau social ?'
    Avez_vous_au_moins_un_compte_sur_un_réseau_social_OUI = models.FloatField(null=True,blank=True) # verbose_name='Avez-vous au moins un compte sur un réseau social ?/OUI'
    Avez_vous_au_moins_un_compte_sur_un_réseau_social_NON = models.FloatField(null=True,blank=True) # verbose_name='Avez-vous au moins un compte sur un réseau social ?/NON'
    col_1_12_Avez_vous_un_contact_téléphonique_1 = models.CharField(max_length=255) # verbose_name='1.12. Avez-vous un contact téléphonique ?.1'
    col_18_Avez_vous_au_moins_un_compte_sur_un_réseau_social = models.FloatField(null=True,blank=True) # verbose_name='18- Avez-vous au moins un compte sur un réseau social ?'
    col_18_Avez_vous_au_moins_un_compte_sur_un_réseau_social_18_1_O = models.FloatField(null=True,blank=True) # verbose_name='18- Avez-vous au moins un compte sur un réseau social ?/18.1. OUI'
    col_18_Avez_vous_au_moins_un_compte_sur_un_réseau_social_18_2_N = models.FloatField(null=True,blank=True) # verbose_name='18- Avez-vous au moins un compte sur un réseau social ?/18.2. NON'
    col_19_Quel_est_le_nombre_de_vos_employés = models.FloatField(null=True,blank=True) # verbose_name='19- Quel est le nombre de vos employés ?'
    col_19_Quel_est_le_nombre_de_vos_employés_Moins_de_5_personnes = models.FloatField(null=True,blank=True) # verbose_name='19- Quel est le nombre de vos employés ?/Moins de 5 personnes'
    col_19_Quel_est_le_nombre_de_vos_employés_Entre_5_et_10_personn = models.FloatField(null=True,blank=True) # verbose_name='19- Quel est le nombre de vos employés ?/Entre 5 et 10 personnes '
    col_19_Quel_est_le_nombre_de_vos_employés_Plus_de_10_personnes = models.FloatField(null=True,blank=True) # verbose_name='19- Quel est le nombre de vos employés ?/Plus de 10 personnes '
    col_18_Si_oui_quel_réseau_social_utilisez_vous_le_plus = models.FloatField(null=True,blank=True) # verbose_name='18- Si oui quel réseau social utilisez-vous le plus ?'
    col_18_Si_oui_quel_réseau_social_utilisez_vous_le_plus_Facebook = models.FloatField(null=True,blank=True) # verbose_name='18- Si oui quel réseau social utilisez-vous le plus ?/Facebook'
    col_18_Si_oui_quel_réseau_social_utilisez_vous_le_plus_WhatsApp = models.FloatField(null=True,blank=True) # verbose_name='18- Si oui quel réseau social utilisez-vous le plus ?/WhatsApp'
    col_18_Si_oui_quel_réseau_social_utilisez_vous_le_plus_X_Twitte = models.FloatField(null=True,blank=True) # verbose_name='18- Si oui quel réseau social utilisez-vous le plus ?/X (Twitter)'
    col_18_Si_oui_quel_réseau_social_utilisez_vous_le_plus_Instagra = models.FloatField(null=True,blank=True) # verbose_name='18- Si oui quel réseau social utilisez-vous le plus ?/Instagram'
    col_18_Si_oui_quel_réseau_social_utilisez_vous_le_plus_Autre = models.FloatField(null=True,blank=True) # verbose_name='18- Si oui quel réseau social utilisez-vous le plus ?/Autre'
    Si_oui_quel_réseau_social_utilisez_vous_le_plus = models.FloatField(null=True,blank=True) # verbose_name='Si oui quel réseau social utilisez-vous le plus ?'
    Si_oui_quel_réseau_social_utilisez_vous_le_plus_Facebook = models.FloatField(null=True,blank=True) # verbose_name='Si oui quel réseau social utilisez-vous le plus ?/Facebook'
    Si_oui_quel_réseau_social_utilisez_vous_le_plus_WhatsApp = models.FloatField(null=True,blank=True) # verbose_name='Si oui quel réseau social utilisez-vous le plus ?/WhatsApp'
    Si_oui_quel_réseau_social_utilisez_vous_le_plus_X_Twitter = models.FloatField(null=True,blank=True) # verbose_name='Si oui quel réseau social utilisez-vous le plus ?/X (Twitter)'
    Si_oui_quel_réseau_social_utilisez_vous_le_plus_Instagram = models.FloatField(null=True,blank=True) # verbose_name='Si oui quel réseau social utilisez-vous le plus ?/Instagram'
    Si_oui_quel_réseau_social_utilisez_vous_le_plus_Autre = models.FloatField(null=True,blank=True) # verbose_name='Si oui quel réseau social utilisez-vous le plus ?/Autre'
    col_19_Si_oui_quel_réseau_social_utilisez_vous_le_plus = models.FloatField(null=True,blank=True) # verbose_name='19- Si oui, quel réseau social utilisez-vous le plus ?'
    col_19_Si_oui_quel_réseau_social_utilisez_vous_le_plus_19_1_Fac = models.FloatField(null=True,blank=True) # verbose_name='19- Si oui, quel réseau social utilisez-vous le plus ?/19.1. Facebook'
    col_19_Si_oui_quel_réseau_social_utilisez_vous_le_plus_19_2_Wha = models.FloatField(null=True,blank=True) # verbose_name='19- Si oui, quel réseau social utilisez-vous le plus ?/19.2. WhatsApp'
    col_19_Si_oui_quel_réseau_social_utilisez_vous_le_plus_19_3_X_T = models.FloatField(null=True,blank=True) # verbose_name='19- Si oui, quel réseau social utilisez-vous le plus ?/19.3. X (Twitter)'
    col_19_Si_oui_quel_réseau_social_utilisez_vous_le_plus_19_4_Ins = models.FloatField(null=True,blank=True) # verbose_name='19- Si oui, quel réseau social utilisez-vous le plus ?/19.4. Instagram'
    col_19_Si_oui_quel_réseau_social_utilisez_vous_le_plus_19_5_Aut = models.FloatField(null=True,blank=True) # verbose_name='19- Si oui, quel réseau social utilisez-vous le plus ?/19.5. Autre'
    col_20_Position_géographique_de_l_atelier_point_GPS = models.FloatField(null=True,blank=True) # verbose_name='20- Position géographique de l'atelier (point GPS)'
    _20_Position_géographique_de_l_atelier_point_GPS_latitude = models.FloatField(null=True,blank=True) # verbose_name='_20- Position géographique de l'atelier (point GPS)_latitude'
    _20_Position_géographique_de_l_atelier_point_GPS_longitude = models.FloatField(null=True,blank=True) # verbose_name='_20- Position géographique de l'atelier (point GPS)_longitude'
    _20_Position_géographique_de_l_atelier_point_GPS_altitude = models.FloatField(null=True,blank=True) # verbose_name='_20- Position géographique de l'atelier (point GPS)_altitude'
    _20_Position_géographique_de_l_atelier_point_GPS_precision = models.FloatField(null=True,blank=True) # verbose_name='_20- Position géographique de l'atelier (point GPS)_precision'
    col_19_Pensez_vous_que_la_promotion_de_vos_marchandises_en_lign = models.FloatField(null=True,blank=True) # verbose_name='19- Pensez-vous que la promotion de vos marchandises en ligne ou services pourrait contribuer à faire évoluer votre activité?'
    Pensez_vous_que_la_promotion_de_vos_marchandises_en_ligne_ou_se = models.FloatField(null=True,blank=True) # verbose_name='Pensez-vous que la promotion de vos marchandises en ligne ou services pourrait contribuer à faire évoluer votre activité ?'
    col_20_Pensez_vous_que_la_promotion_de_vos_marchandises_en_lign = models.FloatField(null=True,blank=True) # verbose_name='20- Pensez-vous que la promotion de vos marchandises en ligne ou services pourrait contribuer à faire évoluer votre activité?'
    col_20_1_Souhaiteriez_vous_être_formé_sur_le_marketing_digital = models.FloatField(null=True,blank=True) # verbose_name='20-1- Souhaiteriez-vous être formé sur le marketing digital ?'
    col_20_Comment_évaluez_vous_vous_même_la_qualité_de_votre_activ = models.FloatField(null=True,blank=True) # verbose_name='20- Comment évaluez-vous vous-même la qualité de votre activité ?'
    Comment_évaluez_vous_vous_même_la_qualité_de_votre_activité = models.FloatField(null=True,blank=True) # verbose_name='Comment évaluez-vous vous-même la qualité de votre activité ?'
    col_1_15_Si_Oui_quel_est_votre_numéro_de_téléphone_principal = models.FloatField(null=True,blank=True) # verbose_name='1.15. Si Oui, quel est votre numéro de téléphone principal'
    col_21_Souhaiteriez_vous_être_formé_sur_l_utilisation_des_servi = models.FloatField(null=True,blank=True) # verbose_name='21-  Souhaiteriez vous être formé sur l'utilisation des services en ligne pour la promotion de vos marchandises ?'
    col_20_2_Combien_seriez_vous_prêt_à_dépenser_pour_votre_formati = models.FloatField(null=True,blank=True) # verbose_name='20-2- Combien seriez-vous prêt à dépenser pour votre formation sur le digital ?'
    col_21_Comment_les_clients_jugent_ils_la_qualité_de_votre_trava = models.FloatField(null=True,blank=True) # verbose_name='21- Comment les clients jugent-ils la qualité de votre travail ?'
    Comment_les_clients_jugent_ils_la_qualité_de_votre_travail = models.FloatField(null=True,blank=True) # verbose_name='Comment les clients jugent-ils la qualité de votre travail ?'
    Comment_les_clients_jugent_ils_la_qualité_de_votre_travail_Très = models.FloatField(null=True,blank=True) # verbose_name='Comment les clients jugent-ils la qualité de votre travail ?/Très Satisfaisant'
    Comment_les_clients_jugent_ils_la_qualité_de_votre_travail_Sati = models.FloatField(null=True,blank=True) # verbose_name='Comment les clients jugent-ils la qualité de votre travail ?/Satisfaisant'
    Comment_les_clients_jugent_ils_la_qualité_de_votre_travail_Moin = models.FloatField(null=True,blank=True) # verbose_name='Comment les clients jugent-ils la qualité de votre travail ?/Moins satisfaisant'
    Comment_les_clients_jugent_ils_la_qualité_de_votre_travail_Je_n = models.FloatField(null=True,blank=True) # verbose_name='Comment les clients jugent-ils la qualité de votre travail ?/Je n'en ai aucune idée '
    col_1_16_Avez_vous_un_adresse_email = models.CharField(max_length=255) # verbose_name='1.16. Avez-vous un adresse email'
    col_22_Combien_seriez_vous_prêt_à_dépenser_pour_votre_formation = models.FloatField(null=True,blank=True) # verbose_name='22-  Combien seriez-vous prêt à dépenser pour votre formation sur le digital ?'
    col_21_Comment_évaluez_vous_vous_même_la_qualité_de_votre_activ = models.FloatField(null=True,blank=True) # verbose_name='21- Comment évaluez-vous vous-même la qualité de votre activité ?'
    col_22_Quel_est_le_nombre_de_vos_employés = models.FloatField(null=True,blank=True) # verbose_name='22- Quel est le nombre de vos employés ?'
    col_22_Quel_est_le_nombre_de_vos_employés_Moins_de_5_personnes = models.FloatField(null=True,blank=True) # verbose_name='22- Quel est le nombre de vos employés ?/Moins de 5 personnes'
    col_22_Quel_est_le_nombre_de_vos_employés_Entre_5_et_10_personn = models.FloatField(null=True,blank=True) # verbose_name='22- Quel est le nombre de vos employés ?/Entre 5 et 10 personnes '
    col_22_Quel_est_le_nombre_de_vos_employés_Plus_de_10_personnes = models.FloatField(null=True,blank=True) # verbose_name='22- Quel est le nombre de vos employés ?/Plus de 10 personnes '
    Quel_est_le_nombre_de_vos_employés = models.FloatField(null=True,blank=True) # verbose_name='Quel est le nombre de vos employés ?'
    Quel_est_le_nombre_de_vos_employés_Moins_de_5_personnes = models.FloatField(null=True,blank=True) # verbose_name='Quel est le nombre de vos employés ?/Moins de 5 personnes'
    Quel_est_le_nombre_de_vos_employés_Entre_5_et_10_personnes = models.FloatField(null=True,blank=True) # verbose_name='Quel est le nombre de vos employés ?/Entre 5 et 10 personnes '
    Quel_est_le_nombre_de_vos_employés_Plus_de_10_personnes = models.FloatField(null=True,blank=True) # verbose_name='Quel est le nombre de vos employés ?/Plus de 10 personnes '
    col_23_Avez_vous_déjà_entendu_parler_de_l_intelligence_artifici = models.FloatField(null=True,blank=True) # verbose_name='23- Avez-vous déjà entendu parler de l'intelligence artificielle ?'
    col_22_Comment_les_clients_jugent_ils_la_qualité_de_votre_trava = models.FloatField(null=True,blank=True) # verbose_name='22- Comment les clients jugent-ils la qualité de votre travail ?'
    col_23_Position_géographique_de_l_atelier = models.FloatField(null=True,blank=True) # verbose_name='23- Position géographique de l'atelier '
    col_1_18_Lieu_d_exercice_de_l_activité_1 = models.CharField(max_length=255) # verbose_name='1.18. Lieu d’exercice de l’activité.1'
    Si_oui_par_quel_moyen_avez_vous_eu_les_informations_sur_l_intel = models.FloatField(null=True,blank=True) # verbose_name='Si oui, par quel moyen avez-vous eu les informations sur l'intelligence artificielle ?'
    col_23_Quel_est_le_nombre_de_vos_employés = models.FloatField(null=True,blank=True) # verbose_name='23- Quel est le nombre de vos employés ?'
    col_23_Quel_est_le_nombre_de_vos_employés_Moins_de_5_personnes = models.FloatField(null=True,blank=True) # verbose_name='23- Quel est le nombre de vos employés ?/Moins de 5 personnes'
    col_23_Quel_est_le_nombre_de_vos_employés_Entre_5_et_10_personn = models.FloatField(null=True,blank=True) # verbose_name='23- Quel est le nombre de vos employés ?/Entre 5 et 10 personnes '
    col_23_Quel_est_le_nombre_de_vos_employés_Plus_de_10_personnes = models.FloatField(null=True,blank=True) # verbose_name='23- Quel est le nombre de vos employés ?/Plus de 10 personnes '
    col_24_Quel_est_le_nombre_de_vos_employés = models.FloatField(null=True,blank=True) # verbose_name='24- Quel est le nombre de vos employés ?'
    col_24_Quel_est_le_nombre_de_vos_employés_24_1_Moins_de_5_perso = models.FloatField(null=True,blank=True) # verbose_name='24- Quel est le nombre de vos employés ?/24.1. Moins de 5 personnes'
    col_24_Quel_est_le_nombre_de_vos_employés_24_2_Entre_5_et_10_pe = models.FloatField(null=True,blank=True) # verbose_name='24- Quel est le nombre de vos employés ?/24.2. Entre 5 et 10 personnes '
    col_24_Quel_est_le_nombre_de_vos_employés_24_3_Plus_de_10_perso = models.FloatField(null=True,blank=True) # verbose_name='24- Quel est le nombre de vos employés ?/24.3. Plus de 10 personnes '
    col_24_Position_géographique_de_l_atelier = models.FloatField(null=True,blank=True) # verbose_name='24- Position géographique de l'atelier '
    col_25_Position_géographique_de_l_atelier_point_GPS = models.FloatField(null=True,blank=True) # verbose_name='25- Position géographique de l'atelier (point GPS)'
    _25_Position_géographique_de_l_atelier_point_GPS_latitude = models.FloatField(null=True,blank=True) # verbose_name='_25- Position géographique de l'atelier (point GPS)_latitude'
    _25_Position_géographique_de_l_atelier_point_GPS_longitude = models.FloatField(null=True,blank=True) # verbose_name='_25- Position géographique de l'atelier (point GPS)_longitude'
    _25_Position_géographique_de_l_atelier_point_GPS_altitude = models.FloatField(null=True,blank=True) # verbose_name='_25- Position géographique de l'atelier (point GPS)_altitude'
    _25_Position_géographique_de_l_atelier_point_GPS_precision = models.FloatField(null=True,blank=True) # verbose_name='_25- Position géographique de l'atelier (point GPS)_precision'
    col_1_17_Si_oui_quel_est_votre_mail_1 = models.FloatField(null=True,blank=True) # verbose_name='1.17. Si oui quel est votre mail.1'
    col_2_12_Disposez_vous_d_un_code_de_conduite_dans_votre_atelier = models.CharField(max_length=255) # verbose_name='2.12 Disposez vous d’un code de conduite dans votre atelier (magasin)?'
    col_2_15_Si_oui_quel_type_de_taxes_payez_vous_1 = models.CharField(max_length=255) # verbose_name='2.15. Si oui, quel type de taxes payez-vous ?.1'
    col_2_14_Etes_vous_disposés_à_légaliser_votre_activité = models.FloatField(null=True,blank=True) # verbose_name='2.14. Etes-vous disposés à légaliser votre activité ?'
    col_2_14_Etes_vous_disposés_à_légaliser_votre_activité_1_Oui = models.FloatField(null=True,blank=True) # verbose_name='2.14. Etes-vous disposés à légaliser votre activité ?/1. Oui'
    col_2_14_Etes_vous_disposés_à_légaliser_votre_activité_2_Non = models.FloatField(null=True,blank=True) # verbose_name='2.14. Etes-vous disposés à légaliser votre activité ?/2. Non'
    col_3_1_Voulez_vous_avoir_des_pages_publicitaires_dédiées_à_vot = models.FloatField(null=True,blank=True) # verbose_name='3.1 Voulez-vous avoir des pages publicitaires dédiées à votre activité ?'
    col_3_2_Souhaiteriez_vous_être_accompagné_d_un_service_numériqu = models.FloatField(null=True,blank=True) # verbose_name='3.2 Souhaiteriez-vous être accompagné d’un service numérique à travers le développement d’une application pour la promotion de vos marchandises ?'
    col_2_12_1_Donnez_nous_le_code_de_conduite_de_votre_atelier_mag = models.CharField(max_length=255) # verbose_name='2.12.1 Donnez nous le code de conduite de votre atelier (magasin)?'
    col_3_3_Quels_objectifs_voulez_vous_atteindre_au_travers_de_cet = models.FloatField(null=True,blank=True) # verbose_name='3.3 Quels objectifs voulez-vous atteindre au travers de cette plateforme ?'
    col_3_3_Si_Oui_combien_seriez_vous_prêt_à_payer_pour_cette_appl = models.FloatField(null=True,blank=True) # verbose_name='3.3. Si Oui combien seriez-vous prêt à payer pour cette application ?'
    col_3_4_Si_Oui_combien_seriez_vous_prêt_à_payer_pour_cette_appl = models.FloatField(null=True,blank=True) # verbose_name='3.4. Si Oui combien seriez-vous prêt à payer pour cette application ?'
    col_3_4_Quels_types_de_contenus_vous_intéresseraient_pour_promo = models.CharField(max_length=255) # verbose_name='3.4 Quels types de contenus vous intéresseraient pour promouvoir votre activité artisanale ? (Plusieurs réponses possibles)'
    col_3_5_Quels_types_de_contenus_vous_intéresseraient_pour_promo = models.FloatField(null=True,blank=True) # verbose_name='3.5 Quels types de contenus vous intéresseraient pour promouvoir votre activité artisanale ? (Plusieurs réponses possibles)'
    col_3_5_Souhaiteriez_vous_être_formé_sur_l_utilisation_des_serv = models.CharField(max_length=255) # verbose_name='3.5 Souhaiteriez-vous être formé sur l’utilisation des services en ligne pour la promotion de vos marchandises ?'
    col_3_6_Souhaiteriez_vous_être_formé_sur_l_utilisation_des_serv = models.FloatField(null=True,blank=True) # verbose_name='3.6 Souhaiteriez-vous être formé sur l’utilisation des services en ligne pour la promotion de vos marchandises ?'
    col_3_6_Si_Oui_combien_seriez_vous_prêt_à_payer_pour_cette_form = models.FloatField(null=True,blank=True) # verbose_name='3.6. Si Oui combien seriez-vous prêt à payer pour cette formation ?'
    col_3_7_Si_Oui_combien_seriez_vous_prêt_à_payer_pour_cette_form = models.FloatField(null=True,blank=True) # verbose_name='3.7. Si Oui combien seriez-vous prêt à payer pour cette formation ?'
    col_3_7_Si_oui_pouvez_vous_indiquer_ces_craintes = models.CharField(max_length=255) # verbose_name='3.7. Si oui, pouvez-vous indiquer ces craintes ?'
    col_3_7_Si_oui_pouvez_vous_indiquer_ces_craintes_1_Anarque = models.FloatField(null=True,blank=True) # verbose_name='3.7. Si oui, pouvez-vous indiquer ces craintes ?/1. Anarque '
    col_3_7_Si_oui_pouvez_vous_indiquer_ces_craintes_2_Piraterie = models.FloatField(null=True,blank=True) # verbose_name='3.7. Si oui, pouvez-vous indiquer ces craintes ?/2. Piraterie '
    col_3_7_Si_oui_pouvez_vous_indiquer_ces_craintes_3_Problème_d_a = models.FloatField(null=True,blank=True) # verbose_name='3.7. Si oui, pouvez-vous indiquer ces craintes ?/3. Problème d’accès à internet '
    col_3_7_Si_oui_pouvez_vous_indiquer_ces_craintes_4_Confidential = models.FloatField(null=True,blank=True) # verbose_name='3.7. Si oui, pouvez-vous indiquer ces craintes ?/4. Confidentialité des données '
    col_3_7_Si_oui_pouvez_vous_indiquer_ces_craintes_5_Difficultés = models.FloatField(null=True,blank=True) # verbose_name='3.7. Si oui, pouvez-vous indiquer ces craintes ?/5. Difficultés d’accès à internet '
    col_3_7_Si_oui_pouvez_vous_indiquer_ces_craintes_6_Autres_Préci = models.FloatField(null=True,blank=True) # verbose_name='3.7. Si oui, pouvez-vous indiquer ces craintes ?/6. Autres(Préciser) '
    col_3_8_Avez_vous_des_craintes_quant_à_l_utilisation_des_servic = models.FloatField(null=True,blank=True) # verbose_name='3.8 Avez-vous des craintes quant à l’utilisation des services en ligne ?'
    col_3_8_Quel_est_selon_vous_l_avantage_d_utiliser_une_plateform = models.CharField(max_length=255) # verbose_name='3.8 Quel est selon vous l’avantage d’utiliser une plateforme de promotion pour vos activités ?'
    col_3_9_Si_oui_pouvez_vous_indiquer_ces_craintes = models.FloatField(null=True,blank=True) # verbose_name='3.9. Si oui, pouvez-vous indiquer ces craintes ?'
    col_3_9_Si_oui_pouvez_vous_indiquer_ces_craintes_1_Anarque = models.FloatField(null=True,blank=True) # verbose_name='3.9. Si oui, pouvez-vous indiquer ces craintes ?/1. Anarque '
    col_3_9_Si_oui_pouvez_vous_indiquer_ces_craintes_2_Piraterie = models.FloatField(null=True,blank=True) # verbose_name='3.9. Si oui, pouvez-vous indiquer ces craintes ?/2. Piraterie '
    col_3_9_Si_oui_pouvez_vous_indiquer_ces_craintes_3_Problème_d_a = models.FloatField(null=True,blank=True) # verbose_name='3.9. Si oui, pouvez-vous indiquer ces craintes ?/3. Problème d’accès à internet '
    col_3_9_Si_oui_pouvez_vous_indiquer_ces_craintes_4_Confidential = models.FloatField(null=True,blank=True) # verbose_name='3.9. Si oui, pouvez-vous indiquer ces craintes ?/4. Confidentialité des données '
    col_3_9_Si_oui_pouvez_vous_indiquer_ces_craintes_5_Difficultés = models.FloatField(null=True,blank=True) # verbose_name='3.9. Si oui, pouvez-vous indiquer ces craintes ?/5. Difficultés d’accès à internet '
    col_3_9_Si_oui_pouvez_vous_indiquer_ces_craintes_6_Autres_Préci = models.FloatField(null=True,blank=True) # verbose_name='3.9. Si oui, pouvez-vous indiquer ces craintes ?/6. Autres(Préciser) '
    col_3_5_1_Si_oui_pouvez_vous_indiquer_ces_craintes_1 = models.CharField(max_length=255) # verbose_name='3.5.1. Si oui, pouvez-vous indiquer ces craintes ?.1'
    col_3_5_1_Si_oui_pouvez_vous_indiquer_ces_craintes_1_Anarque_1 = models.FloatField(null=True,blank=True) # verbose_name='3.5.1. Si oui, pouvez-vous indiquer ces craintes ?/1. Anarque .1'
    col_3_9_Avez_vous_déjà_entendu_parler_de_l_intelligence_artific = models.CharField(max_length=255) # verbose_name='3.9 Avez-vous déjà entendu parler de l’intelligence artificielle ?'
    col_3_10_Quel_est_selon_vous_l_avantage_d_utiliser_une_platefor = models.FloatField(null=True,blank=True) # verbose_name='3.10 Quel est selon vous l’avantage d’utiliser une plateforme de promotion pour vos activités ?'
    col_3_10_Si_oui_par_quel_moyen_avez_vous_eu_les_informations_su = models.CharField(max_length=255) # verbose_name='3.10 Si oui, par quel moyen avez-vous eu les informations sur l’intelligence artificielle ?'
    col_3_11_Avez_vous_déjà_entendu_parler_de_l_intelligence_artifi = models.FloatField(null=True,blank=True) # verbose_name='3.11 Avez-vous déjà entendu parler de l’intelligence artificielle ?'
    col_3_11_Avez_vous_déjà_utilisé_l_intelligence_artificielle_dan = models.CharField(max_length=255) # verbose_name='3.11 Avez-vous déjà utilisé l’intelligence artificielle dans le cadre de votre activité ? '
    col_3_12_Si_oui_par_quel_moyen_avez_vous_eu_les_informations_su = models.FloatField(null=True,blank=True) # verbose_name='3.12 Si oui, par quel moyen avez-vous eu les informations sur l’intelligence artificielle ?'
    col_4_Avez_vous_un_compte_sur_un_réseau_social_1 = models.CharField(max_length=255) # verbose_name='4. Avez-vous un compte sur un réseau social ?.1'
    col_3_13_Avez_vous_déjà_utilisé_l_intelligence_artificielle_dan = models.FloatField(null=True,blank=True) # verbose_name='3.13 Avez-vous déjà utilisé l’intelligence artificielle dans le cadre de votre activité ? '
    col_4_1_Avez_vous_un_compte_sur_un_réseau_social = models.FloatField(null=True,blank=True) # verbose_name='4.1. Avez-vous un compte sur un réseau social ?'
    col_4_1_Avez_vous_un_compte_sur_un_réseau_social_1_Oui = models.FloatField(null=True,blank=True) # verbose_name='4.1. Avez-vous un compte sur un réseau social ?/1. Oui'
    col_4_1_Avez_vous_un_compte_sur_un_réseau_social_2_Non = models.FloatField(null=True,blank=True) # verbose_name='4.1. Avez-vous un compte sur un réseau social ?/2. Non'
    col_4_2_Si_oui_quel_réseau_social_utilisez_vous_le_plus_pour_fa = models.FloatField(null=True,blank=True) # verbose_name='4.2 Si oui, quel réseau social utilisez-vous le plus pour faire la promotion de articles ?'
    col_4_3_Quels_types_de_supports_utilisez_vous_pour_faire_la_pro = models.FloatField(null=True,blank=True) # verbose_name='4.3 Quels types de supports utilisez vous pour faire la promotion de vos articles ?'
    col_4_4_Pensez_vous_que_la_promotion_de_vos_marchandises_ou_ser = models.FloatField(null=True,blank=True) # verbose_name='4.4 Pensez-vous que la promotion de vos marchandises ou services en ligne pourrait contribuer à faire évoluer votre activité ?'
    col_4_5_Quels_sont_les_moyens_de_paiement_que_vous_utilisez_dan = models.FloatField(null=True,blank=True) # verbose_name='4.5 Quels sont les moyens de paiement que vous utilisez dans le cadre de votre activité ?'
    col_4_6_Comment_préférez_vous_recevoir_des_informations_sur_de = models.FloatField(null=True,blank=True) # verbose_name='4.6 Comment préférez-vous recevoir des informations sur de nouveaux services ou promotions liés à l'artisanat ?'
    col_4_11_Quels_sont_vos_différentes_catégories_de_clients_1 = models.CharField(max_length=255) # verbose_name='4.11 Quels sont vos différentes catégories de clients ?.1'
    col_4_13_Avez_vous_un_service_de_livraison_1 = models.CharField(max_length=255) # verbose_name='4.13 Avez-vous un service de livraison ?.1'
    col_4_15_Comment_se_fait_les_livraisons = models.CharField(max_length=255) # verbose_name='4.15 Comment se fait les livraisons ?'
    col_4_15_Comment_se_fait_les_livraisons_1_Déplacement_à_pied = models.FloatField(null=True,blank=True) # verbose_name='4.15 Comment se fait les livraisons ?/1. Déplacement à pied '
    col_4_15_Comment_se_fait_les_livraisons_2_Automobile = models.FloatField(null=True,blank=True) # verbose_name='4.15 Comment se fait les livraisons ?/2. Automobile '
    col_4_15_Comment_se_fait_les_livraisons_3_Moto = models.FloatField(null=True,blank=True) # verbose_name='4.15 Comment se fait les livraisons ?/3. Moto'
    col_4_15_Comment_se_fait_les_livraisons_4_Camion = models.FloatField(null=True,blank=True) # verbose_name='4.15 Comment se fait les livraisons ?/4. Camion '
    col_4_15_Comment_se_fait_les_livraisons_5_Bateau = models.FloatField(null=True,blank=True) # verbose_name='4.15 Comment se fait les livraisons ?/5. Bateau '
    col_4_15_Comment_se_fait_les_livraisons_6_Autres_Préciser = models.FloatField(null=True,blank=True) # verbose_name='4.15 Comment se fait les livraisons ?/6. Autres (Préciser) '
    col_4_15_Comment_se_font_les_livraisons_1 = models.CharField(max_length=255) # verbose_name='4.15 Comment se font les livraisons ?.1'
    col_4_15_Comment_se_font_les_livraisons_1_Déplacement_à_pied_1 = models.FloatField(null=True,blank=True) # verbose_name='4.15 Comment se font les livraisons ?/1. Déplacement à pied .1'
    col_4_15_Comment_se_font_les_livraisons_2_Automobile_1 = models.FloatField(null=True,blank=True) # verbose_name='4.15 Comment se font les livraisons ?/2. Automobile .1'
    col_4_15_Comment_se_font_les_livraisons_3_Moto_1 = models.FloatField(null=True,blank=True) # verbose_name='4.15 Comment se font les livraisons ?/3. Moto.1'
    col_4_15_Comment_se_font_les_livraisons_4_Camion_1 = models.FloatField(null=True,blank=True) # verbose_name='4.15 Comment se font les livraisons ?/4. Camion .1'
    col_4_15_Comment_se_font_les_livraisons_5_Bateau_1 = models.FloatField(null=True,blank=True) # verbose_name='4.15 Comment se font les livraisons ?/5. Bateau .1'
    col_4_15_Comment_se_font_les_livraisons_6_Autres_Préciser_1 = models.FloatField(null=True,blank=True) # verbose_name='4.15 Comment se font les livraisons ?/6. Autres (Préciser) .1'
    # _id = models.IntegerField() # verbose_name='_id'
    # _uuid = models.CharField(max_length=255) # verbose_name='_uuid'
    # _submission_time = models.DateTimeField(null=True,blank=True) # verbose_name='_submission_time'
    # _validation_status = models.CharField(max_length=255) # verbose_name='_validation_status'
    # _notes = models.FloatField(null=True,blank=True) # verbose_name='_notes'
    # _status = models.CharField(max_length=255) # verbose_name='_status'
    _submitted_by = models.FloatField(null=True,blank=True) # verbose_name='_submitted_by'
    # _version = models.CharField(max_length=255) # verbose_name='__version__'
    # _tags = models.FloatField(null=True,blank=True) # verbose_name='_tags'
    # _index = models.IntegerField() # verbose_name='_index'

    def __str__(self):
        return f"{self.col_1_11_Nom_et_prénoms_du_répondant} {self.col_0_3_NOM_ET_PRENOMS_DE_L_ENQUETEUR} "
