# Generated by Django 5.0.6 on 2024-05-18 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan', '0002_alter_artisan_o_6_date_de_l_enquete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artisan',
            name='Avez_vous_au_moins_un_compte_sur_un_réseau_social',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='Avez_vous_au_moins_un_compte_sur_un_réseau_social_NON',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='Avez_vous_au_moins_un_compte_sur_un_réseau_social_OUI',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='Avez_vous_un_numéro_de_téléphone',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='Avez_vous_un_numéro_de_téléphone_NON',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='Avez_vous_un_numéro_de_téléphone_OUI',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='CIVILITÉ',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='Combien_de_clients_pourriez_vous_avoir_par_mois',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='Combien_de_clients_pourriez_vous_avoir_par_mois_Entre_10_et_25',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='Combien_de_clients_pourriez_vous_avoir_par_mois_Moins_de_10_cli',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='Combien_de_clients_pourriez_vous_avoir_par_mois_Plus_de_25_clie',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='Combien_peut_vous_rapporter_votre_activité_par_mois',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='Combien_peut_vous_rapporter_votre_activité_par_mois_Entre_100_0',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='Combien_peut_vous_rapporter_votre_activité_par_mois_Entre_50_00',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='Combien_peut_vous_rapporter_votre_activité_par_mois_Moins_de_50',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='Combien_peut_vous_rapporter_votre_activité_par_mois_Plus_de_200',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='Comment_les_clients_jugent_ils_la_qualité_de_votre_travail',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='Comment_les_clients_jugent_ils_la_qualité_de_votre_travail_Je_n',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='Comment_les_clients_jugent_ils_la_qualité_de_votre_travail_Moin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='Comment_les_clients_jugent_ils_la_qualité_de_votre_travail_Sati',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='Comment_les_clients_jugent_ils_la_qualité_de_votre_travail_Très',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='Comment_voyez_vous_votre_activité_dans_les_années_à_venir',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='Comment_voyez_vous_votre_activité_dans_les_années_à_venir_Augme',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='Comment_voyez_vous_votre_activité_dans_les_années_à_venir_Le_pr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='Comment_voyez_vous_votre_activité_dans_les_années_à_venir_Une_e',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='Comment_évaluez_vous_le_développement_actuel_de_votre_activité',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='Comment_évaluez_vous_vous_même_la_qualité_de_votre_activité',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='De_quel_pays_êtes_vous',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='De_quel_pays_êtes_vous_Autre',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='De_quel_pays_êtes_vous_Côte_d_Ivoire',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='Depuis_combien_d_années_exercez_vous_ce_métier',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='Depuis_combien_d_années_exercez_vous_ce_métier_Entre_1_et_4_ans',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='Depuis_combien_d_années_exercez_vous_ce_métier_Moins_d_un_an',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='Depuis_combien_d_années_exercez_vous_ce_métier_Plus_de_5_ans',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='La_ville_quartier',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='La_ville_quartier_Abidjan',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='La_ville_quartier_Autre_préciser',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='La_ville_quartier_Bouaké',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='La_ville_quartier_Korhogo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='La_ville_quartier_San_Pédro',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='La_ville_quartier_Yamoussoukro',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='NOM_ET_PRÉNOM_S',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='Pensez_vous_que_la_promotion_de_vos_marchandises_en_ligne_ou_se',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='Pensez_vous_que_votre_activité_contribue_au_développement_socio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='Quel_est_le_nombre_de_vos_employés',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='Quel_est_le_nombre_de_vos_employés_Entre_5_et_10_personnes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='Quel_est_le_nombre_de_vos_employés_Moins_de_5_personnes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='Quel_est_le_nombre_de_vos_employés_Plus_de_10_personnes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='Quel_est_votre_numéro_de_téléphone_principal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='Quel_métier_exercez_vous',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='Quelle_est_la_source_de_financement_qui_a_permis_le_démarrage_d',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='Quelle_est_âge_avez_vous',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='Quelle_est_âge_avez_vous_18_25_ans',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='Quelle_est_âge_avez_vous_25_35_ans',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='Quelle_est_âge_avez_vous_35_45_ans',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='Quelle_est_âge_avez_vous_45_ans_et_plus',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='Quelles_sont_les_difficultés_que_vous_avez_rencontré_les_premie',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='Si_oui_par_quel_moyen_avez_vous_eu_les_informations_sur_l_intel',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='Si_oui_quel_est_votre_numéro_de_téléphone_principal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='Si_oui_quel_réseau_social_utilisez_vous_le_plus',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='Si_oui_quel_réseau_social_utilisez_vous_le_plus_Autre',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='Si_oui_quel_réseau_social_utilisez_vous_le_plus_Facebook',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='Si_oui_quel_réseau_social_utilisez_vous_le_plus_Instagram',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='Si_oui_quel_réseau_social_utilisez_vous_le_plus_WhatsApp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='Si_oui_quel_réseau_social_utilisez_vous_le_plus_X_Twitter',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='Si_oui_quel_type_de_taxe_payez_vous',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='Si_oui_quel_type_de_taxe_payez_vous_a_Taxe_communale',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='Si_oui_quel_type_de_taxe_payez_vous_b_Patente',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='Si_oui_quel_type_de_taxe_payez_vous_c_TVA',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='Utilisez_vous_internet_pour_la_promotion_de_votre_activité',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='Utilisez_vous_internet_pour_la_promotion_de_votre_activité_Non',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='Utilisez_vous_internet_pour_la_promotion_de_votre_activité_OUI',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='_1_19_Position_GPS_de_l_atelier_Point_GPS_altitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='_1_19_Position_GPS_de_l_atelier_Point_GPS_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='_1_19_Position_GPS_de_l_atelier_Point_GPS_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='_1_19_Position_GPS_de_l_atelier_Point_GPS_precision',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='_20_Position_géographique_de_l_atelier_point_GPS_altitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='_20_Position_géographique_de_l_atelier_point_GPS_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='_20_Position_géographique_de_l_atelier_point_GPS_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='_20_Position_géographique_de_l_atelier_point_GPS_precision',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='_25_Position_géographique_de_l_atelier_point_GPS_altitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='_25_Position_géographique_de_l_atelier_point_GPS_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='_25_Position_géographique_de_l_atelier_point_GPS_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='_25_Position_géographique_de_l_atelier_point_GPS_precision',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='_submitted_by',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_10_Quelle_est_la_source_de_financement_qui_a_permis_le_déma',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_10_Êtes_vous_satisfait_des_résultats_actuels_de_votre_activ',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_11_Comment_évaluez_vous_le_développement_actuel_de_votre_ac',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_11_Quelles_sont_les_difficultés_que_vous_avez_rencontrées_l',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_11_Quelles_sont_les_difficultés_que_vous_rencontrez_actuell',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_12_Combien_peut_vous_rapporter_votre_activité_par_mois',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_12_Combien_peut_vous_rapporter_votre_activité_par_mois_Entr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_12_Combien_peut_vous_rapporter_votre_activité_par_mois_Moin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_12_Combien_peut_vous_rapporter_votre_activité_par_mois_Plus',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_12_Comment_voyez_vous_le_développement_de_votre_activité_da',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_13_Quelle_est_la_source_de_financement_qui_a_permis_le_déma',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_13_Quelles_sont_les_difficultés_que_vous_avez_rencontrées_l',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_13_Utilisez_vous_internet_pour_la_promotion_de_votre_activi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_14_Avez_vous_au_moins_un_compte_sur_un_réseau_social',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_14_Avez_vous_au_moins_un_compte_sur_un_réseau_social_NON',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_14_Avez_vous_au_moins_un_compte_sur_un_réseau_social_OUI',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_14_Combien_peut_vous_rapporter_votre_activité_par_mois',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_14_Combien_peut_vous_rapporter_votre_activité_par_mois_Entr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_14_Combien_peut_vous_rapporter_votre_activité_par_mois_Moin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_14_Combien_peut_vous_rapporter_votre_activité_par_mois_Plus',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_14_Quelles_sont_les_difficultés_que_vous_avez_rencontrées_l',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_15_Combien_de_clients_pourriez_vous_avoir_par_mois',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_15_Combien_de_clients_pourriez_vous_avoir_par_mois_Entre_10',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_15_Combien_de_clients_pourriez_vous_avoir_par_mois_Moins_de',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_15_Combien_de_clients_pourriez_vous_avoir_par_mois_Plus_de',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_15_Combien_peut_vous_rapporter_votre_activité_par_mois',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_15_Si_oui_quel_réseau_social_utilisez_vous_le_plus',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_15_Si_oui_quel_réseau_social_utilisez_vous_le_plus_Autre',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_15_Si_oui_quel_réseau_social_utilisez_vous_le_plus_Facebook',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_15_Si_oui_quel_réseau_social_utilisez_vous_le_plus_Instagra',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_15_Si_oui_quel_réseau_social_utilisez_vous_le_plus_WhatsApp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_15_Si_oui_quel_réseau_social_utilisez_vous_le_plus_X_Twitte',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_16_Payez_vous_des_taxes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_16_Payez_vous_des_taxes_16_1_NON',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_16_Payez_vous_des_taxes_16_1_OUI',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_16_Pensez_vous_que_la_promotion_de_vos_marchandises_en_lign',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_16_Utilisez_vous_internet_pour_la_promotion_de_votre_activi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_17_Avez_vous_au_moins_un_compte_sur_un_réseau_social',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_17_Avez_vous_au_moins_un_compte_sur_un_réseau_social_NON',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_17_Avez_vous_au_moins_un_compte_sur_un_réseau_social_OUI',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_17_Souhaiteriez_vous_être_formé_sur_l_utilisation_des_servi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_17_Utilisez_vous_internet_pour_la_promotion_de_votre_activi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_18_Avez_vous_au_moins_un_compte_sur_un_réseau_social',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_18_Avez_vous_au_moins_un_compte_sur_un_réseau_social_18_1_O',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_18_Avez_vous_au_moins_un_compte_sur_un_réseau_social_18_2_N',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_18_Combien_seriez_vous_prêt_à_dépenser_pour_votre_formation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_18_Si_oui_quel_réseau_social_utilisez_vous_le_plus',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_18_Si_oui_quel_réseau_social_utilisez_vous_le_plus_Autre',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_18_Si_oui_quel_réseau_social_utilisez_vous_le_plus_Facebook',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_18_Si_oui_quel_réseau_social_utilisez_vous_le_plus_Instagra',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_18_Si_oui_quel_réseau_social_utilisez_vous_le_plus_WhatsApp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_18_Si_oui_quel_réseau_social_utilisez_vous_le_plus_X_Twitte',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_19_Pensez_vous_que_la_promotion_de_vos_marchandises_en_lign',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_19_Quel_est_le_nombre_de_vos_employés',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_19_Quel_est_le_nombre_de_vos_employés_Entre_5_et_10_personn',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_19_Quel_est_le_nombre_de_vos_employés_Moins_de_5_personnes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_19_Quel_est_le_nombre_de_vos_employés_Plus_de_10_personnes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_19_Si_oui_quel_réseau_social_utilisez_vous_le_plus',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_19_Si_oui_quel_réseau_social_utilisez_vous_le_plus_19_1_Fac',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_19_Si_oui_quel_réseau_social_utilisez_vous_le_plus_19_2_Wha',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_19_Si_oui_quel_réseau_social_utilisez_vous_le_plus_19_3_X_T',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_19_Si_oui_quel_réseau_social_utilisez_vous_le_plus_19_4_Ins',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_19_Si_oui_quel_réseau_social_utilisez_vous_le_plus_19_5_Aut',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_1_13_Si_Oui_quel_est_votre_numéro_de_téléphone_principal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_1_15_Si_Oui_quel_est_votre_numéro_de_téléphone_Whasapp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_1_15_Si_Oui_quel_est_votre_numéro_de_téléphone_principal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_1_17_Si_oui_quel_est_votre_mail_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_1_CIVILITÉ',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_20_1_Souhaiteriez_vous_être_formé_sur_le_marketing_digital',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_20_2_Combien_seriez_vous_prêt_à_dépenser_pour_votre_formati',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_20_Comment_évaluez_vous_vous_même_la_qualité_de_votre_activ',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_20_Pensez_vous_que_la_promotion_de_vos_marchandises_en_lign',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_20_Position_géographique_de_l_atelier_point_GPS',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_21_Comment_les_clients_jugent_ils_la_qualité_de_votre_trava',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_21_Comment_évaluez_vous_vous_même_la_qualité_de_votre_activ',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_21_Souhaiteriez_vous_être_formé_sur_l_utilisation_des_servi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_22_Combien_seriez_vous_prêt_à_dépenser_pour_votre_formation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_22_Comment_les_clients_jugent_ils_la_qualité_de_votre_trava',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_22_Quel_est_le_nombre_de_vos_employés',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_22_Quel_est_le_nombre_de_vos_employés_Entre_5_et_10_personn',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_22_Quel_est_le_nombre_de_vos_employés_Moins_de_5_personnes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_22_Quel_est_le_nombre_de_vos_employés_Plus_de_10_personnes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_23_Avez_vous_déjà_entendu_parler_de_l_intelligence_artifici',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_23_Position_géographique_de_l_atelier',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_23_Quel_est_le_nombre_de_vos_employés',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_23_Quel_est_le_nombre_de_vos_employés_Entre_5_et_10_personn',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_23_Quel_est_le_nombre_de_vos_employés_Moins_de_5_personnes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_23_Quel_est_le_nombre_de_vos_employés_Plus_de_10_personnes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_24_Position_géographique_de_l_atelier',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_24_Quel_est_le_nombre_de_vos_employés',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_24_Quel_est_le_nombre_de_vos_employés_24_1_Moins_de_5_perso',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_24_Quel_est_le_nombre_de_vos_employés_24_2_Entre_5_et_10_pe',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_24_Quel_est_le_nombre_de_vos_employés_24_3_Plus_de_10_perso',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_25_Position_géographique_de_l_atelier_point_GPS',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_2_14_Etes_vous_disposés_à_légaliser_votre_activité',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_2_14_Etes_vous_disposés_à_légaliser_votre_activité_1_Oui',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_2_14_Etes_vous_disposés_à_légaliser_votre_activité_2_Non',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_2_NOM_ET_PRÉNOM_S',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_3_10_Quel_est_selon_vous_l_avantage_d_utiliser_une_platefor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_3_11_Avez_vous_déjà_entendu_parler_de_l_intelligence_artifi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_3_12_Si_oui_par_quel_moyen_avez_vous_eu_les_informations_su',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_3_13_Avez_vous_déjà_utilisé_l_intelligence_artificielle_dan',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_3_1_Voulez_vous_avoir_des_pages_publicitaires_dédiées_à_vot',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_3_2_Souhaiteriez_vous_être_accompagné_d_un_service_numériqu',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_3_3_Quels_objectifs_voulez_vous_atteindre_au_travers_de_cet',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_3_3_Si_Oui_combien_seriez_vous_prêt_à_payer_pour_cette_appl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_3_4_Si_Oui_combien_seriez_vous_prêt_à_payer_pour_cette_appl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_3_5_1_Si_oui_pouvez_vous_indiquer_ces_craintes_1_Anarque',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_3_5_1_Si_oui_pouvez_vous_indiquer_ces_craintes_1_Anarque_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_3_5_1_Si_oui_pouvez_vous_indiquer_ces_craintes_2_Piraterie',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_3_5_1_Si_oui_pouvez_vous_indiquer_ces_craintes_3_Problème_d',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_3_5_1_Si_oui_pouvez_vous_indiquer_ces_craintes_4_Confidenti',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_3_5_1_Si_oui_pouvez_vous_indiquer_ces_craintes_5_Difficulté',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_3_5_1_Si_oui_pouvez_vous_indiquer_ces_craintes_6_Autres_Pré',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_3_5_Quels_types_de_contenus_vous_intéresseraient_pour_promo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_3_6_Si_Oui_combien_seriez_vous_prêt_à_payer_pour_cette_form',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_3_6_Souhaiteriez_vous_être_formé_sur_l_utilisation_des_serv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_3_7_Si_Oui_combien_seriez_vous_prêt_à_payer_pour_cette_form',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_3_7_Si_oui_pouvez_vous_indiquer_ces_craintes_1_Anarque',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_3_7_Si_oui_pouvez_vous_indiquer_ces_craintes_2_Piraterie',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_3_7_Si_oui_pouvez_vous_indiquer_ces_craintes_3_Problème_d_a',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_3_7_Si_oui_pouvez_vous_indiquer_ces_craintes_4_Confidential',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_3_7_Si_oui_pouvez_vous_indiquer_ces_craintes_5_Difficultés',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_3_7_Si_oui_pouvez_vous_indiquer_ces_craintes_6_Autres_Préci',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_3_8_Avez_vous_des_craintes_quant_à_l_utilisation_des_servic',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_3_9_Si_oui_pouvez_vous_indiquer_ces_craintes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_3_9_Si_oui_pouvez_vous_indiquer_ces_craintes_1_Anarque',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_3_9_Si_oui_pouvez_vous_indiquer_ces_craintes_2_Piraterie',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_3_9_Si_oui_pouvez_vous_indiquer_ces_craintes_3_Problème_d_a',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_3_9_Si_oui_pouvez_vous_indiquer_ces_craintes_4_Confidential',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_3_9_Si_oui_pouvez_vous_indiquer_ces_craintes_5_Difficultés',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_3_9_Si_oui_pouvez_vous_indiquer_ces_craintes_6_Autres_Préci',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_3_Quelle_est_votre_tranche_d_âge',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_3_Quelle_est_votre_tranche_d_âge_3_1_Moins_de_25_ans',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_3_Quelle_est_votre_tranche_d_âge_3_2_25_35m4_ans',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_3_Quelle_est_votre_tranche_d_âge_3_3_35_44_ans',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_3_Quelle_est_votre_tranche_d_âge_3_4_44_à_55_ans',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_3_Quelle_est_votre_tranche_d_âge_3_5_Plus_de_55_ans',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_3_Quelle_est_âge_avez_vous',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_3_Quelle_est_âge_avez_vous_18_25_ans',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_3_Quelle_est_âge_avez_vous_25_35_ans',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_3_Quelle_est_âge_avez_vous_35_45_ans',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_3_Quelle_est_âge_avez_vous_45_ans_et_plus',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_4_11_Quels_sont_vos_différentes_catégories_de_clients_1_Par',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_4_11_Quels_sont_vos_différentes_catégories_de_clients_2_Soc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_4_11_Quels_sont_vos_différentes_catégories_de_clients_3_Fon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_4_11_Quels_sont_vos_différentes_catégories_de_clients_4_Aut',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_4_14_Si_oui_quel_moyen_utilisez_vous_pour_vos_livraisons_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_4_14_Si_oui_quel_moyen_utilisez_vous_pour_vos_livraisons_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_4_14_Si_oui_quel_moyen_utilisez_vous_pour_vos_livraisons_3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_4_14_Si_oui_quel_moyen_utilisez_vous_pour_vos_livraisons_4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_4_14_Si_oui_quel_moyen_utilisez_vous_pour_vos_livraisons_5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_4_15_Comment_se_fait_les_livraisons_1_Déplacement_à_pied',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_4_15_Comment_se_fait_les_livraisons_2_Automobile',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_4_15_Comment_se_fait_les_livraisons_3_Moto',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_4_15_Comment_se_fait_les_livraisons_4_Camion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_4_15_Comment_se_fait_les_livraisons_5_Bateau',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_4_15_Comment_se_fait_les_livraisons_6_Autres_Préciser',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_4_15_Comment_se_font_les_livraisons_1_Déplacement_à_pied',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_4_15_Comment_se_font_les_livraisons_1_Déplacement_à_pied_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_4_15_Comment_se_font_les_livraisons_2_Automobile',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_4_15_Comment_se_font_les_livraisons_2_Automobile_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_4_15_Comment_se_font_les_livraisons_3_Moto',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_4_15_Comment_se_font_les_livraisons_3_Moto_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_4_15_Comment_se_font_les_livraisons_4_Camion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_4_15_Comment_se_font_les_livraisons_4_Camion_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_4_15_Comment_se_font_les_livraisons_5_Bateau',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_4_15_Comment_se_font_les_livraisons_5_Bateau_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_4_15_Comment_se_font_les_livraisons_6_Autres_Préciser',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_4_15_Comment_se_font_les_livraisons_6_Autres_Préciser_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_4_1_Avez_vous_un_compte_sur_un_réseau_social',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_4_1_Avez_vous_un_compte_sur_un_réseau_social_1_Oui',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_4_1_Avez_vous_un_compte_sur_un_réseau_social_2_Non',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_4_2_Si_oui_quel_réseau_social_utilisez_vous_le_plus_pour_fa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_4_3_Quels_types_de_supports_utilisez_vous_pour_faire_la_pro',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_4_4_Pensez_vous_que_la_promotion_de_vos_marchandises_ou_ser',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_4_5_Quels_sont_les_moyens_de_paiement_que_vous_utilisez_dan',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_4_6_Comment_préférez_vous_recevoir_des_informations_sur_de',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_4_9_Quels_types_d_accompagnement_souhaiteriez_vous_1_Accuei',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_4_9_Quels_types_d_accompagnement_souhaiteriez_vous_2_Evalua',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_4_9_Quels_types_d_accompagnement_souhaiteriez_vous_3_Commun',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_4_9_Quels_types_d_accompagnement_souhaiteriez_vous_4_Répara',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_4_9_Quels_types_d_accompagnement_souhaiteriez_vous_5_Autres',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_4_De_quel_pays_êtes_vous',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_4_De_quel_pays_êtes_vous_4_1_Côte_d_Ivoire',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_4_De_quel_pays_êtes_vous_4_2_CEDEAO',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_4_De_quel_pays_êtes_vous_4_3_Hors_CEDEAO_tous_les_pays',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_5_La_ville',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_5_La_ville_5_1_Abidjan',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_5_La_ville_5_2_Yamoussoukro',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_5_La_ville_5_3_Bouaké',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_5_La_ville_5_4_San_Pédro',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_5_La_ville_5_5_Korhogo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_5_La_ville_5_6_Autre_préciser',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_5_La_ville_quartier',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_5_La_ville_quartier_Abidjan',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_5_La_ville_quartier_Autre_préciser',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_5_La_ville_quartier_Bouaké',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_5_La_ville_quartier_Korhogo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_5_La_ville_quartier_San_Pédro',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_5_La_ville_quartier_Yamoussoukro',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_6_1_Quel_est_votre_numéro_de_téléphone_principal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_6_Avez_vous_un_numéro_de_téléphone',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_6_Avez_vous_un_numéro_de_téléphone_6_1_OUI',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_6_Avez_vous_un_numéro_de_téléphone_6_2_NON',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_6_Avez_vous_un_numéro_de_téléphone_OUI',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_7_Quel_métier_exercez_vous',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_7_Quel_métier_exercez_vous_7_10_La_charpenterie',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_7_Quel_métier_exercez_vous_7_11_Spécialiste_en_froid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_7_Quel_métier_exercez_vous_7_12_La_bijouterie',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_7_Quel_métier_exercez_vous_7_13_La_boucherie',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_7_Quel_métier_exercez_vous_7_14_Vente_de_marchandises_diver',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_7_Quel_métier_exercez_vous_7_15_La_restauration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_7_Quel_métier_exercez_vous_7_16_La_vitrerie',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_7_Quel_métier_exercez_vous_7_17_Autre',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_7_Quel_métier_exercez_vous_7_1_La_mécanique',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_7_Quel_métier_exercez_vous_7_2_La_menuiserie',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_7_Quel_métier_exercez_vous_7_3_La_maçonnerie',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_7_Quel_métier_exercez_vous_7_4_La_couture',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_7_Quel_métier_exercez_vous_7_5_La_tapisserie',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_7_Quel_métier_exercez_vous_7_6_La_ferronnerie',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_7_Quel_métier_exercez_vous_7_7_La_coiffure',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_7_Quel_métier_exercez_vous_7_8_L_électronique_réparateur_TV',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_7_Quel_métier_exercez_vous_7_9_La_briqueterie',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_8_Depuis_combien_d_années_exercez_vous_ce_métier',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_8_Depuis_combien_d_années_exercez_vous_ce_métier_8_1_Moins',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_8_Depuis_combien_d_années_exercez_vous_ce_métier_8_2_Entre',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_8_Depuis_combien_d_années_exercez_vous_ce_métier_8_3_Plus_d',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_9_Pensez_vous_que_votre_activité_contribue_au_développement',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='col_9_Êtes_vous_satisfait_des_résultats_actuels_de_votre_activi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='Êtes_vous_satisfait_des_résultats_actuels_de_votre_activité',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
