# Generated by Django 5.0.6 on 2024-05-18 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='date of creation')),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('delete_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='date of creation')),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('delete_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('speciality', models.CharField(choices=[('DAS', "Dévéloppement d'application et E-services"), ('RSI', 'Réseaux et sécurité informatique '), ('BD', 'Base de donnée'), ('BD', 'Base de donnée'), ('MMX', 'Multi médias et communication'), ('CMD', 'Communication marqueting digital'), ('ATD', '...')])),
                ('is_ceo', models.BooleanField(default=False)),
                ('department', models.CharField(choices=[('CEO', 'Dierecteur général'), ('CP', 'Coordinateur de projet'), ('DS', 'Directeur de service'), ('DP', 'Directeur de département'), ('CS', 'Chef de service'), ('CL', 'Collaborateur')])),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='date of creation')),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('delete_at', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.company')),
            ],
        ),
    ]
